import type { CaseStudyEntry } from "./types";

export const caseStudies: CaseStudyEntry[] = [
  {
    id: "zerodha", company: "Zerodha", category: "Indian Startups", industry: "Fintech / Stockbroking", factType: "documented",
    problem: "Retail stockbroking in India was expensive, with high commissions eating into small investors' returns.",
    solution: "A discount broking platform charging flat, low fees per trade instead of percentage-based commissions.",
    customer: "Retail investors and traders across India, especially tech-savvy, cost-conscious individuals.",
    businessModel: "Flat-fee brokerage with a direct, no-advisory, self-service trading platform.",
    revenueModel: "Flat brokerage fees per executed trade, plus revenue from other financial products.",
    growth: "Grew to become one of India's largest stockbrokers by account count, reportedly without large-scale paid advertising, relying significantly on word-of-mouth and content/education-led trust-building.",
    competition: "Faced competition from traditional full-service brokers and other discount brokers that emerged afterward.",
    challenges: "Operating in a heavily regulated industry while building trust with first-time retail investors new to direct trading.",
    lessons: ["A simpler, transparent pricing model can disrupt an industry built on complex, high fees.", "Building financial literacy content can be both a trust-builder and an acquisition channel.", "Bootstrapped growth is possible even in capital-intensive-seeming industries."],
  },
  {
    id: "zoho", company: "Zoho", category: "SaaS", industry: "Business Software", factType: "documented",
    problem: "Small and mid-sized businesses needed affordable, integrated software tools without expensive enterprise pricing.",
    solution: "A broad suite of affordable, integrated SaaS products (CRM, email, finance, HR) for SMBs.",
    customer: "Small and mid-sized businesses globally, priced and positioned as an alternative to expensive enterprise software.",
    businessModel: "SaaS subscription across many integrated product lines.",
    revenueModel: "Recurring subscription fees across its suite of products.",
    growth: "Famously bootstrapped, reportedly building a large, profitable global SaaS business without raising venture capital, reinvesting profits into R&D and expansion.",
    competition: "Competes with Salesforce, Microsoft, and other enterprise and SMB software providers.",
    challenges: "Competing against well-funded, larger competitors while maintaining profitability without external capital.",
    lessons: ["Bootstrapping can build a globally competitive company given enough patience and reinvestment discipline.", "A broad, integrated product suite can create switching-cost based retention.", "Affordability-focused positioning can carve out a large underserved segment (SMBs) ignored by enterprise-focused competitors."],
  },
  {
    id: "swiggy", company: "Swiggy", category: "Marketplace", industry: "Food Delivery", factType: "documented",
    problem: "Customers wanted convenient food delivery from a wide range of restaurants, with reliable logistics.",
    solution: "A food delivery marketplace connecting restaurants, delivery partners, and customers through an app.",
    customer: "Urban consumers seeking convenient food delivery across Indian cities.",
    businessModel: "Marketplace connecting restaurants and consumers, with its own delivery fleet (unlike pure listing sites).",
    revenueModel: "Commission from restaurant partners per order, plus delivery fees and advertising revenue from restaurants.",
    growth: "Expanded rapidly across Indian cities, later diversifying into instant grocery delivery (Instamart) and other adjacent services.",
    competition: "Competes primarily with Zomato in the Indian food delivery market.",
    challenges: "Managing complex last-mile logistics, maintaining delivery partner satisfaction, and navigating intense price-based competition.",
    lessons: ["Owning the logistics layer (not just listings) can be a key differentiator in delivery marketplaces.", "Expanding into adjacent categories (grocery) can leverage existing delivery infrastructure.", "Intense competition in delivery marketplaces often compresses margins, making operational efficiency critical."],
  },
  {
    id: "nykaa", company: "Nykaa", category: "E-commerce", industry: "Beauty & Personal Care", factType: "documented",
    problem: "Indian consumers lacked a trustworthy place to discover and buy a wide range of genuine beauty products with expert guidance.",
    solution: "A curated beauty e-commerce platform combining product variety with content (reviews, tutorials) to build trust.",
    customer: "Indian consumers, primarily women, seeking genuine beauty and personal care products with guidance.",
    businessModel: "E-commerce marketplace plus owned private-label brands.",
    revenueModel: "Product sales margin, plus brand partnerships and advertising on the platform.",
    growth: "Grew from an online beauty retailer into a broader beauty and fashion platform, eventually going public via IPO.",
    competition: "Competes with general e-commerce platforms, other beauty-focused platforms, and offline retail.",
    challenges: "Maintaining authenticity/trust in a category prone to counterfeit concerns, and building owned-brand margins alongside marketplace commissions.",
    lessons: ["Content and trust-building (reviews, tutorials) can be a genuine differentiator in categories with authenticity concerns.", "A marketplace can evolve into owning higher-margin private-label brands over time.", "Category-specific curation can outperform generic e-commerce for specialised products."],
  },
  {
    id: "cred", company: "CRED", category: "Fintech", industry: "Consumer Finance", factType: "documented",
    problem: "Paying credit card bills was treated as a chore, with no incentive or reward for financial discipline.",
    solution: "An app that rewards users for paying credit card bills on time, targeting a premium, creditworthy user base.",
    customer: "Creditworthy, financially disciplined consumers with good credit card repayment habits.",
    businessModel: "Freemium rewards app expanding into other financial products (lending, payments) over time.",
    revenueModel: "Initially reward-driven with limited direct monetisation, later expanding into financial product revenue streams.",
    growth: "Built a premium brand positioning and grew its user base by specifically targeting a creditworthy, high-value niche rather than mass-market users.",
    competition: "Competes indirectly with traditional banking apps and other fintech reward platforms.",
    challenges: "Monetising a free rewards-based user base while maintaining its premium brand positioning.",
    lessons: ["Deliberately narrow targeting (only creditworthy users) can build a strong, premium brand identity.", "A single strong core loop (bill payment + rewards) can be the foundation before broader product expansion.", "Premium positioning requires sustained design and experience consistency to justify exclusivity."],
  },
  {
    id: "dmart", company: "DMart", category: "Retail", industry: "Organized Retail", factType: "documented",
    problem: "Indian consumers needed affordable, reliable access to groceries and household goods through organized retail.",
    solution: "A value-retail chain focused on everyday low prices through operational efficiency rather than premium positioning.",
    customer: "Value-conscious Indian households seeking affordable groceries and household essentials.",
    businessModel: "Large-format retail stores with owned real estate in many cases, focused on cost efficiency.",
    revenueModel: "Retail margin on high-volume product sales.",
    growth: "Expanded steadily across India, known for prioritising profitability and operational discipline over rapid, unprofitable expansion.",
    competition: "Competes with other organized retail chains and traditional kirana stores.",
    challenges: "Balancing expansion pace with maintaining the operational efficiency that drives its low-price model.",
    lessons: ["Operational efficiency and disciplined cost management can be a durable competitive advantage in retail.", "Prioritising profitable unit economics over rapid expansion can build a more resilient business.", "Thin margins at scale, if operationally sound, can still build a highly profitable business."],
  },
  {
    id: "meesho", company: "Meesho", category: "Marketplace", industry: "Social Commerce", factType: "documented",
    problem: "Many individuals, especially homemakers, wanted to earn income through reselling but lacked access to suppliers or e-commerce tools.",
    solution: "A social commerce platform enabling individuals to resell products sourced from the platform via their own social networks (like WhatsApp).",
    customer: "Individual resellers (many homemakers) and end consumers reached through social reselling networks.",
    businessModel: "Marketplace connecting suppliers, resellers, and end consumers.",
    revenueModel: "Commission and fees from suppliers and transactions on the platform.",
    growth: "Grew rapidly by tapping into underserved segments (small-town and tier 2/3 city resellers) that larger e-commerce platforms hadn't deeply penetrated.",
    competition: "Competes with other e-commerce and social commerce platforms targeting similar underserved segments.",
    challenges: "Managing quality control and logistics across a highly distributed network of small resellers.",
    lessons: ["Identifying an underserved customer segment (resellers, not just end buyers) can unlock a large new market.", "Social/network-based distribution can be a powerful, low-cost acquisition channel.", "Enabling micro-entrepreneurship can create strong platform loyalty among supply-side participants."],
  },
  {
    id: "airbnb", company: "Airbnb", category: "Marketplace", industry: "Hospitality", factType: "documented",
    problem: "Travellers wanted more affordable, personal lodging options than traditional hotels, especially during high-demand periods.",
    solution: "A marketplace allowing individuals to rent out spare space in their homes to travellers.",
    customer: "Budget-conscious travellers and hosts seeking extra income from unused space.",
    businessModel: "Marketplace connecting hosts and guests, taking a commission on bookings.",
    revenueModel: "Service fees charged to both hosts and guests on each booking.",
    growth: "Grew from a small apartment-listing MVP into a global hospitality marketplace spanning millions of listings worldwide.",
    competition: "Competes with traditional hotel chains and other short-term rental platforms.",
    challenges: "Building trust and safety systems for a marketplace involving strangers staying in each other's personal spaces, plus navigating varying local regulations globally.",
    lessons: ["Starting with a tiny, manual MVP (the founders' own apartment) can validate a model before any major investment.", "Trust and safety systems are critical infrastructure for peer-to-peer marketplaces.", "A niche initial use case (renting air mattresses) can evolve into a much larger platform once validated."],
  },
  {
    id: "whatsapp", company: "WhatsApp", category: "Consumer", industry: "Messaging / Communication", factType: "documented",
    problem: "Consumers needed a fast, reliable way to send messages without relying on costly SMS.",
    solution: "A simple, reliable cross-platform messaging app focused intensely on speed and reliability.",
    customer: "Global smartphone users seeking free or low-cost messaging.",
    businessModel: "Initially a small paid app, later free with a focus on massive scale and network effects.",
    revenueModel: "Historically minimal direct monetisation during rapid growth phase; broader monetisation (business messaging) developed later.",
    growth: "Achieved massive global adoption, reportedly reaching billions of users, driven heavily by network effects as more contacts joined.",
    competition: "Competes with other messaging apps and platform-native messaging features.",
    challenges: "Maintaining reliability and simplicity at a massive global scale while resisting pressure to add excessive features.",
    lessons: ["Deliberate, sustained focus on one core value (fast, reliable messaging) can drive durable network-effect-based growth.", "Resisting feature bloat early on can be as important as adding the right features later.", "A network effect becomes an increasingly strong moat as adoption scales."],
  },
  {
    id: "mcdonalds", company: "McDonald's", category: "Food", industry: "Quick Service Restaurants", factType: "documented",
    problem: "Consumers wanted consistent, fast, affordable food regardless of location.",
    solution: "A highly standardised, franchise-driven fast food system ensuring consistency across every location.",
    customer: "Mass-market consumers seeking fast, consistent, affordable food globally.",
    businessModel: "Franchise model combined with real estate strategy (McDonald's owns or leases much of the real estate its franchisees operate on).",
    revenueModel: "Franchise fees, royalties on franchisee sales, and rental income from franchisee-operated properties.",
    growth: "Expanded globally through a franchise model, enabling rapid scale without McDonald's directly operating every restaurant.",
    competition: "Competes with other global and local fast food chains.",
    challenges: "Maintaining consistent quality and experience across thousands of independently operated franchise locations worldwide.",
    lessons: ["Standardised Standard Operating Procedures (SOPs) are what make consistent quality possible at massive scale.", "A franchise model can enable rapid global expansion without the parent company bearing all operational capital costs.", "Operational excellence can be as much a competitive advantage as the product itself."],
  },
  {
    id: "illustrative-d2c-snacks", company: "Illustrative: Regional Snacks D2C Brand", category: "Food", industry: "D2C Food & Beverage", factType: "illustrative",
    problem: "Urban professionals living away from their hometowns missed authentic regional snacks unavailable in generic supermarkets.",
    solution: "A D2C subscription box delivering curated, authentic regional Indian snacks directly to consumers nationwide.",
    customer: "Urban, nostalgic professionals aged 25-40 living away from their home region.",
    businessModel: "D2C subscription box with direct online sales, skipping traditional retail.",
    revenueModel: "Monthly subscription fees plus one-time gift box purchases.",
    growth: "Illustrative growth driven by influencer marketing and word-of-mouth within diaspora communities in metro cities.",
    competition: "Illustrative competition from generic snack brands and other regional specialty D2C startups.",
    challenges: "Illustrative challenges include maintaining product freshness during shipping and managing seasonal demand fluctuations.",
    lessons: ["A specific, emotionally resonant customer insight (nostalgia) can anchor a focused D2C brand.", "Subscription models provide predictable recurring revenue but require strong retention to be sustainable.", "This case is illustrative — used to demonstrate analytical frameworks, not a real documented company."],
  },
  {
    id: "illustrative-b2b-saas", company: "Illustrative: B2B Inventory SaaS", category: "SaaS", industry: "B2B Software", factType: "illustrative",
    problem: "Small retail businesses were managing inventory manually through Excel, leading to frequent stockouts and overstock.",
    solution: "An affordable, simple SaaS inventory management tool specifically designed for small retailers.",
    customer: "Small retail businesses with 5-50 employees, currently relying on manual or Excel-based inventory tracking.",
    businessModel: "SaaS subscription with tiered pricing based on inventory volume.",
    revenueModel: "Monthly/annual subscription fees.",
    growth: "Illustrative growth through narrowing ICP after discovering fast-growing e-commerce retailers converted far better than generic small businesses.",
    competition: "Illustrative competition from larger, more complex enterprise inventory systems and other small-business-focused tools.",
    challenges: "Illustrative challenges include educating a non-technical customer base and competing against free spreadsheet-based alternatives.",
    lessons: ["Narrowing an ICP based on real conversion data can dramatically improve sales efficiency.", "Serving an underserved segment (small retailers) ignored by enterprise-focused competitors can be a viable strategy.", "This case is illustrative — used to demonstrate analytical frameworks, not a real documented company."],
  },
];
