import type { FormulaEntry } from "./types";

export const formulas: FormulaEntry[] = [
  // Finance
  { id: "profit", name: "Profit", category: "Finance", expression: "Profit = Revenue − Cost", explanation: "What remains after subtracting all costs from revenue.", example: "Revenue ₹10,00,000 − Cost ₹7,00,000 = Profit ₹3,00,000." },
  { id: "gross-margin", name: "Gross Margin %", category: "Finance", expression: "Gross Margin % = (Gross Profit ÷ Revenue) × 100", explanation: "The percentage of revenue left after direct production costs (COGS).", example: "Gross Profit ₹6,00,000 ÷ Revenue ₹10,00,000 × 100 = 60%." },
  { id: "net-margin", name: "Net Margin %", category: "Finance", expression: "Net Margin % = (Net Profit ÷ Revenue) × 100", explanation: "The percentage of revenue left after ALL costs, including overhead, interest, and tax.", example: "Net Profit ₹1,00,000 ÷ Revenue ₹10,00,000 × 100 = 10%." },
  { id: "gross-profit", name: "Gross Profit", category: "Finance", expression: "Gross Profit = Revenue − COGS", explanation: "Profit before accounting for operating expenses.", example: "Revenue ₹10,00,000 − COGS ₹4,00,000 = ₹6,00,000." },
  { id: "operating-profit", name: "Operating Profit", category: "Finance", expression: "Operating Profit = Gross Profit − Operating Expenses", explanation: "Profit from core operations before interest and tax.", example: "Gross Profit ₹6,00,000 − OPEX ₹4,00,000 = ₹2,00,000." },
  { id: "net-profit", name: "Net Profit", category: "Finance", expression: "Net Profit = Operating Profit − Interest/Tax", explanation: "The final profit after every cost, including interest and tax.", example: "Operating Profit ₹2,00,000 − Interest/Tax ₹50,000 = ₹1,50,000." },
  { id: "break-even-units", name: "Break-even Units", category: "Finance", expression: "Break-even Units = Fixed Costs ÷ Contribution per Unit", explanation: "The sales volume needed to cover all costs before profit begins.", example: "Fixed Costs ₹2,00,000 ÷ Contribution ₹400 = 500 units." },
  { id: "contribution-margin", name: "Contribution per Unit", category: "Finance", expression: "Contribution per Unit = Selling Price − Variable Cost per Unit", explanation: "The amount each unit sold contributes toward covering fixed costs.", example: "Selling Price ₹1,000 − Variable Cost ₹600 = ₹400." },
  { id: "balance-sheet-equation", name: "Balance Sheet Equation", category: "Finance", expression: "Assets = Liabilities + Equity", explanation: "The fundamental accounting identity that must always balance.", example: "Assets ₹10,00,000 = Liabilities ₹4,00,000 + Equity ₹6,00,000." },
  { id: "cash-flow", name: "Cash Flow", category: "Finance", expression: "Cash Flow = Cash Received − Cash Paid Out", explanation: "The actual movement of cash, which can differ from recorded profit.", example: "Cash Received ₹6,00,000 − Cash Paid ₹7,00,000 = −₹1,00,000 (negative, a cash crunch)." },
  { id: "burn-rate", name: "Burn Rate", category: "Finance", expression: "Burn Rate = Monthly Cash Outflow − Monthly Cash Inflow", explanation: "The rate at which a company depletes its cash reserves each month.", example: "Outflow ₹15,00,000 − Inflow ₹5,00,000 = ₹10,00,000/month burn." },
  { id: "runway", name: "Runway", category: "Finance", expression: "Runway = Cash Available ÷ Monthly Net Burn", explanation: "How many months a company can operate before running out of cash.", example: "₹50,00,000 cash ÷ ₹10,00,000 monthly burn = 5 months runway." },
  { id: "inventory-turnover", name: "Inventory Turnover", category: "Finance", expression: "Inventory Turnover = COGS ÷ Average Inventory Value", explanation: "How many times inventory is sold and replaced over a period.", example: "COGS ₹24,00,000 ÷ Average Inventory ₹4,00,000 = 6 times/year." },
  { id: "net-gst-payable", name: "Net GST Payable", category: "Finance", expression: "Net GST Payable = Output GST − Input Tax Credit", explanation: "The net GST a business owes the government after crediting GST already paid on purchases.", example: "Output GST ₹80,000 − Input Tax Credit ₹55,000 = ₹25,000." },
  { id: "post-money-valuation", name: "Post-money Valuation", category: "Finance", expression: "Post-money Valuation = Pre-money Valuation + Investment Amount", explanation: "A company's valuation immediately after a new investment is added.", example: "Pre-money ₹9 crore + Investment ₹1 crore = ₹10 crore." },
  { id: "investor-ownership", name: "Investor Ownership %", category: "Finance", expression: "Investor Ownership % = (Investment ÷ Post-money Valuation) × 100", explanation: "The percentage of the company an investor owns after a funding round.", example: "Investment ₹1 crore ÷ Post-money ₹10 crore × 100 = 10%." },
  // Marketing
  { id: "conversion-rate", name: "Conversion Rate", category: "Marketing", expression: "Conversion Rate % = (Conversions ÷ Visitors/Leads) × 100", explanation: "The percentage of visitors or leads who complete a desired action.", example: "50 purchases ÷ 1,000 visitors × 100 = 5%." },
  { id: "roas", name: "ROAS (Return on Ad Spend)", category: "Marketing", expression: "ROAS = Revenue from Ads ÷ Ad Spend", explanation: "Revenue generated for every rupee spent on advertising.", example: "₹4,00,000 revenue ÷ ₹1,00,000 ad spend = 4x ROAS." },
  { id: "channel-cac", name: "Channel CAC", category: "Marketing", expression: "Channel CAC = Spend on Channel ÷ Customers Acquired from Channel", explanation: "The cost-effectiveness of acquiring a customer through a specific marketing channel.", example: "₹50,000 spend ÷ 100 customers = ₹500 Channel CAC." },
  { id: "funnel-conversion", name: "Funnel Stage Conversion", category: "Marketing", expression: "Stage Conversion % = (Advancing to Next Stage ÷ Entering This Stage) × 100", explanation: "The percentage of prospects that move from one funnel stage to the next.", example: "400 demos ÷ 1,000 leads × 100 = 40% conversion to demo stage." },
  { id: "referral-rate", name: "Referral Rate", category: "Marketing", expression: "Referral Rate % = (New Customers from Referrals ÷ Total Existing Customers) × 100", explanation: "The percentage of your existing customer base generating new customers via referral.", example: "500 referred customers ÷ 10,000 existing × 100 = 5%." },
  // Sales
  { id: "sales-conversion-rate", name: "Sales Conversion Rate", category: "Sales", expression: "Conversion Rate % = (Customers ÷ Leads) × 100", explanation: "The percentage of leads that become paying customers.", example: "50 customers ÷ 1,000 leads × 100 = 5%." },
  { id: "average-order-value", name: "Average Order Value", category: "Sales", expression: "Average Order Value = Total Revenue ÷ Number of Orders", explanation: "The average amount a customer spends per transaction.", example: "₹25,00,000 revenue ÷ 50 orders = ₹50,000 AOV." },
  { id: "sales-cac", name: "CAC (Sales & Marketing)", category: "Sales", expression: "CAC = (Total Sales + Marketing Cost) ÷ New Customers", explanation: "The average combined sales and marketing cost to acquire one new customer.", example: "₹5,00,000 spend ÷ 50 customers = ₹10,000 CAC." },
  // Growth
  { id: "churn-rate", name: "Churn Rate", category: "Growth", expression: "Churn Rate % = (Lost Customers ÷ Starting Customers) × 100", explanation: "The percentage of customers who stop using/buying over a period.", example: "80 lost ÷ 1,000 starting × 100 = 8%." },
  { id: "retention-rate", name: "Retention Rate", category: "Growth", expression: "Retention Rate % = (Remaining Customers ÷ Starting Customers) × 100", explanation: "The percentage of customers who continue over a period — the inverse of churn.", example: "920 remaining ÷ 1,000 starting × 100 = 92%." },
  { id: "ltv", name: "LTV (Lifetime Value)", category: "Growth", expression: "LTV = Average Revenue per Customer × Customer Lifetime", explanation: "The total value a business expects to earn from one customer over their lifetime.", example: "₹500/month × 20 months = ₹10,000 LTV." },
  { id: "ltv-cac-ratio", name: "LTV : CAC Ratio", category: "Growth", expression: "LTV : CAC Ratio = LTV ÷ CAC", explanation: "A key health check for unit economics; a ratio of 3:1 or higher is often considered healthy.", example: "LTV ₹10,000 ÷ CAC ₹2,500 = 4:1." },
  { id: "payback-period", name: "Payback Period", category: "Growth", expression: "Payback Period = CAC ÷ Monthly Revenue per Customer", explanation: "The time needed to recover the cost of acquiring a customer.", example: "CAC ₹2,500 ÷ ₹500/month = 5 months." },
  { id: "mrr", name: "MRR (Monthly Recurring Revenue)", category: "Growth", expression: "MRR = Number of Subscribers × Average Monthly Price", explanation: "The predictable monthly subscription revenue a business collects.", example: "1,000 subscribers × ₹1,000 = ₹10,00,000 MRR." },
  { id: "arr", name: "ARR (Annual Recurring Revenue)", category: "Growth", expression: "ARR = MRR × 12", explanation: "The yearly equivalent of MRR, used to describe SaaS business scale.", example: "MRR ₹10,00,000 × 12 = ₹1,20,00,000 ARR." },
  { id: "arpu", name: "ARPU", category: "Growth", expression: "ARPU = Total Revenue ÷ Number of Users", explanation: "The average revenue generated per user over a period.", example: "₹10,00,000 ÷ 2,000 users = ₹500 ARPU." },
  { id: "activation-rate", name: "Activation Rate", category: "Growth", expression: "Activation Rate % = (Users Reaching Aha Moment ÷ Total Sign-ups) × 100", explanation: "The percentage of new users who experience the product's core value.", example: "350 activated ÷ 1,000 sign-ups × 100 = 35%." },
  // Operations
  { id: "break-even-units-ops", name: "Break-even Units (Operations view)", category: "Operations", expression: "Break-even Units = Fixed Costs ÷ (Selling Price − Variable Cost per Unit)", explanation: "The operational sales volume needed before profit begins.", example: "₹5,00,000 Fixed Costs ÷ ₹1,800 Contribution = ~278 units." },
  { id: "inventory-turnover-ops", name: "Inventory Turnover (Operations)", category: "Operations", expression: "Inventory Turnover = COGS ÷ Average Inventory Value", explanation: "How efficiently inventory is being sold and replaced relative to its value.", example: "COGS ₹12,00,000 ÷ Average Inventory ₹1,00,000 = 12 times/year." },
  { id: "working-capital", name: "Working Capital", category: "Operations", expression: "Working Capital = Current Assets − Current Liabilities", explanation: "The money available for day-to-day operations.", example: "₹5,00,000 current assets − ₹2,00,000 current liabilities = ₹3,00,000." },
  // Startup
  { id: "tam-sam-som", name: "TAM → SAM → SOM", category: "Startup", expression: "SAM = TAM × (% realistically serviceable)\nSOM = SAM × (% realistically obtainable)", explanation: "A funnel for sizing a market from the total opportunity down to a realistic near-term target.", example: "TAM 10 crore users → SAM 2 crore (urban, paying) → SOM 4 lakh (realistic 2-year capture)." },
  { id: "validation-signal", name: "Validation Signal Strength", category: "Startup", expression: "Weak: opinions\nMedium: sign-ups\nStrong: pre-payments", explanation: "A simple way to judge how reliable your market validation evidence really is.", example: "100 waitlist sign-ups (medium) with 20 pre-paid deposits (strong) is a solid validation signal." },
  { id: "sean-ellis-pmf", name: "Sean Ellis PMF Test", category: "Startup", expression: "40%+ of surveyed active users saying 'very disappointed' without the product = strong PMF signal", explanation: "A simple survey-based test for gauging product-market fit.", example: "45 of 100 surveyed users say 'very disappointed' — a strong PMF signal." },
];
