import type { Lesson } from "../types";

export const phase05Lessons: Lesson[] = [
  {
    id: "day-29", day: 29, phaseId: "marketing", slug: "what-is-marketing",
    title: "What Is Marketing?",
    objective: "Understand marketing as the practice of creating awareness and desire for value you've already built.",
    concept: "Marketing is the set of activities that identify customer needs, communicate how your product meets them, and build enough awareness and trust that customers choose you. It exists to connect real value to the people who need it.",
    simpleExplanation: "Marketing is not 'just ads.' It includes positioning, messaging, content, branding, PR, and paid promotion — all aimed at making the right customer aware, interested, and confident enough to buy.",
    analogy: "If your product is a great movie, marketing is the trailer, posters, and reviews that get people into the theatre to watch it.",
    businessExample: "Dove's marketing focuses on 'real beauty' messaging rather than just listing soap ingredients — connecting emotionally with its target audience beyond the product's technical features.",
    indiaExample: "Fevicol's long-running witty, memorable ad campaigns built massive brand recall in India, turning a simple adhesive into a household name through consistent, clever marketing.",
    commonMistake: "Treating marketing as something you do only AFTER building the product, instead of understanding the customer and market from the very beginning (which should inform the product itself).",
    exercise: { prompt: "Pick a product you own. Identify: what marketing message made you first aware of it, and what made you trust it enough to buy?", answer: "Example: Awareness came from an Instagram ad; trust came from seeing multiple positive reviews and a friend's recommendation before purchase." },
    caseStudy: "A new D2C snack brand had a great product but zero initial sales. After shifting marketing focus from generic 'healthy snacks' messaging to specific founder storytelling about why the snacks were created (relatable, authentic content), engagement and sales both increased — showing marketing's power even without changing the product.",
    founderQuestion: "If your product disappeared from the market tomorrow, what single marketing message would you want customers to remember most?",
    quiz: [
      { id: "d29q1", question: "What is marketing fundamentally about?", options: ["Only running paid ads", "Connecting real value to the people who need it, through awareness and trust", "Designing logos", "Setting prices"], correctIndex: 1, explanation: "Marketing encompasses far more than ads — it's about awareness, trust, and communication of real value." },
      { id: "d29q2", question: "Why is it a mistake to think about marketing only AFTER building the product?", options: ["Marketing is irrelevant to product decisions", "Customer and market understanding should inform the product itself from the start", "Marketing is illegal before launch", "Products never need marketing"], correctIndex: 1, explanation: "Early market understanding should shape what you build, not just how you promote it afterward." },
      { id: "d29q3", question: "What changed the snack brand's sales trajectory?", options: ["A price cut", "Shifting to authentic founder storytelling instead of generic messaging", "Adding more flavours", "Changing the packaging material"], correctIndex: 1, explanation: "More relatable, specific messaging improved engagement without any product change." },
    ],
    takeaways: ["Marketing connects real value to the people who need it.", "It includes positioning, branding, content, and promotion — not just ads.", "Market understanding should inform the product from the start.", "Authentic, specific messaging often outperforms generic claims."],
    rememberThis: "Marketing is the trailer that gets people into the theatre to watch your movie.",
  },
  {
    id: "day-30", day: 30, phaseId: "marketing", slug: "stp",
    title: "STP: Segmentation, Targeting, Positioning",
    objective: "Learn the classic STP framework for focusing marketing effort effectively.",
    concept: "Segmentation divides a broad market into distinct groups with shared characteristics. Targeting selects which segment(s) to focus on. Positioning defines how you want your product to be perceived in that target segment's mind relative to alternatives.",
    simpleExplanation: "You can't market to 'everyone' effectively. STP forces you to pick a specific slice of the market and define a clear, memorable place in their minds.",
    analogy: "STP is like choosing a single lane to specialise in on a crowded highway rather than trying to drive in every lane at once — specialisation lets you move faster and stand out.",
    businessExample: "Nike segments by activity/lifestyle (runners, basketball players, casual wear), targets performance-driven athletes as a core segment, and positions itself as the brand of elite performance and achievement ('Just Do It').",
    indiaExample: "Patanjali segmented the Indian FMCG market by consumers seeking 'natural/ayurvedic' alternatives, targeted health-conscious and value-conscious households, and positioned itself as an affordable, trustworthy natural alternative to international brands.",
    mnemonic: { label: "STP", breakdown: ["S = Segmentation (divide the market)", "T = Targeting (choose your segment)", "P = Positioning (define your unique place in their mind)"] },
    commonMistake: "Skipping segmentation and targeting, and jumping straight to a vague positioning statement like 'best quality for everyone' — which means nothing to anyone specifically.",
    exercise: { prompt: "For a premium bicycle brand, write one sentence each for Segmentation, Targeting, and Positioning.", answer: "Example: Segmentation — divide cyclists by purpose (commuters, fitness enthusiasts, competitive racers). Targeting — focus on urban fitness enthusiasts aged 25-40. Positioning — 'the bike that makes your daily ride feel like training for a race.'" },
    caseStudy: "A new skincare brand initially marketed 'for everyone, every skin type.' Sales were slow and messaging felt generic. After segmenting by skin concern and targeting specifically 'oily, acne-prone skin in humid climates,' with positioning as 'the skincare line built for India's humidity,' both relevance and conversion improved sharply.",
    founderQuestion: "If you had to pick just ONE narrow segment to dominate before expanding, which would give you the fastest path to loyal, vocal customers?",
    quiz: [
      { id: "d30q1", question: "What does the 'T' in STP stand for?", options: ["Trust", "Targeting", "Transaction", "Trends"], correctIndex: 1, explanation: "Targeting means choosing which specific segment(s) to focus marketing on." },
      { id: "d30q2", question: "Why is 'best quality for everyone' a weak positioning statement?", options: ["It's too short", "It's too vague to be memorable or relevant to any specific group", "It's illegal to claim", "It costs too much to say"], correctIndex: 1, explanation: "Vague, universal claims fail to create a specific, memorable place in any particular customer's mind." },
      { id: "d30q3", question: "What change improved the skincare brand's results?", options: ["Lowering prices", "Narrowing segmentation/targeting and sharpening positioning around a specific need", "Adding more product variants", "Changing the brand name"], correctIndex: 1, explanation: "Specific, relevant positioning for a defined segment outperformed a generic, universal message." },
    ],
    takeaways: ["STP = Segmentation (divide), Targeting (choose), Positioning (define your place in mind).", "Trying to market to 'everyone' usually means resonating with no one specifically.", "Specific, narrow positioning tends to outperform broad, vague claims.", "Positioning should clearly differentiate you from alternatives in the target's mind."],
    rememberThis: "Segment the market, target your slice, position yourself clearly in their mind.",
  },
  {
    id: "day-31", day: 31, phaseId: "marketing", slug: "branding",
    title: "Branding",
    objective: "Understand what a brand really is and why it matters beyond logos and colours.",
    concept: "A brand is the sum of all perceptions, emotions, and associations a customer has about your business — built through every interaction, not just visual design. Strong brands create trust, loyalty, and the ability to charge a premium.",
    simpleExplanation: "Your logo is not your brand. Your brand is what people FEEL and THINK when they hear your name — built through consistent experience over time.",
    analogy: "A brand is like a person's reputation — you can't fully control it, but every action (good or bad) shapes what others believe about you over time.",
    businessExample: "Apple's brand represents simplicity, premium design, and innovation — reinforced consistently across products, stores, packaging, and even customer service tone, not just its logo.",
    indiaExample: "Tata's brand represents trust and reliability across unrelated industries (salt, cars, steel, software) — built over a century of consistent ethical business practice, not a single clever ad.",
    commonMistake: "Believing branding is just visual design (logo, colours, fonts). Real branding is built through consistent customer experience, values, and communication over time — design is just one visible layer.",
    exercise: { prompt: "Pick 2 brands you trust deeply. For each, describe in one sentence what you FEEL when you think of them, and what specific experiences built that feeling.", answer: "Example: 'Amul' feels wholesome and trustworthy — built through decades of consistent quality, honest advertising, and reliability in Indian households." },
    caseStudy: "A startup spent heavily on a polished logo and website but neglected customer service response times. Despite the visual polish, customer trust eroded due to slow, inconsistent support — proving that branding built only on visuals, without consistent experience, is fragile.",
    founderQuestion: "If a stranger asked 10 of your customers to describe your business in one word, what word would you WANT them to say — and does your current experience actually deliver that?",
    quiz: [
      { id: "d31q1", question: "What is a brand, fundamentally?", options: ["Just a logo and colour scheme", "The sum of perceptions and emotions customers associate with your business", "A legal registration", "A marketing budget"], correctIndex: 1, explanation: "Brand is built from cumulative experience and perception, not visual design alone." },
      { id: "d31q2", question: "What built Tata's brand reputation over a century?", options: ["A single viral ad", "Consistent ethical business practice across many industries", "Low prices only", "Aggressive advertising spend"], correctIndex: 1, explanation: "Long-term consistent trustworthy behaviour, not a single campaign, built Tata's reputation." },
      { id: "d31q3", question: "Why did the startup with a polished logo still lose customer trust?", options: ["The logo was ugly", "Inconsistent, slow customer service undermined the visual branding", "They spent too much on design", "Their website crashed"], correctIndex: 1, explanation: "Branding requires consistent experience, not just strong visual design." },
    ],
    takeaways: ["A brand is built from cumulative customer perception and experience, not just visuals.", "Consistency across every touchpoint builds or breaks trust over time.", "Visual design is one layer of branding, not the whole thing.", "Strong brands enable trust, loyalty, and premium pricing."],
    rememberThis: "Your brand is what people feel about you when you're not in the room.",
  },
  {
    id: "day-32", day: 32, phaseId: "marketing", slug: "positioning",
    title: "Positioning",
    objective: "Learn to craft a clear, differentiated positioning statement for your product.",
    concept: "Positioning is the specific, deliberate place you want your product to occupy in the customer's mind relative to alternatives — answering 'why you, instead of anyone else, for this specific need?'",
    simpleExplanation: "Good positioning is simple enough to say in one sentence and specific enough that it couldn't apply to a competitor.",
    analogy: "Positioning is like staking a flag on a hill no one else has claimed — if everyone can plant the same flag, it's not real positioning.",
    businessExample: "Volvo has positioned itself around 'safety' for decades — a single, clear, consistently reinforced claim that few competitors can credibly challenge.",
    indiaExample: "boAt positioned itself as affordable, youthful, India-first audio gear — distinct from premium international brands and generic cheap alternatives alike.",
    formula: { name: "Positioning Statement Template", expression: "For [target customer], [Brand] is the [category] that [key differentiator], unlike [main alternative].", workedExample: "For busy urban professionals, CRED is the credit-card payment app that rewards you for paying bills on time, unlike traditional banking apps that treat it as a chore." },
    commonMistake: "Trying to claim multiple positioning attributes at once ('we're the cheapest AND the most premium AND the fastest') — diluted positioning confuses customers and is rarely believable.",
    exercise: { prompt: "Using the positioning template, write a one-sentence positioning statement for a budget airline targeting first-time flyers.", answer: "Example: 'For first-time flyers on a budget, [Airline] is the airline that makes flying simple and affordable with zero hidden fees, unlike traditional airlines that confuse you with complex pricing.'" },
    caseStudy: "A new mattress startup initially tried to claim 'most comfortable, most affordable, most durable' simultaneously. Customers found the messaging confusing and forgettable. Narrowing to a single clear position — 'the mattress designed specifically for hot Indian summers, with cooling technology' — made the brand instantly memorable and differentiated.",
    founderQuestion: "If you had to delete every claim about your product except ONE, which single claim would you keep — and is it something no competitor can credibly say?",
    quiz: [
      { id: "d32q1", question: "What makes positioning effective?", options: ["Claiming to be the best at everything", "Being simple, specific, and hard for competitors to credibly copy", "Using as many adjectives as possible", "Changing it frequently"], correctIndex: 1, explanation: "Narrow, specific, defensible claims create memorable, believable positioning." },
      { id: "d32q2", question: "What has Volvo consistently positioned itself around?", options: ["Speed", "Luxury", "Safety", "Affordability"], correctIndex: 2, explanation: "Volvo has built decades of brand equity around a single consistent safety claim." },
      { id: "d32q3", question: "Why did narrowing the mattress brand's positioning help?", options: ["It made the product cheaper to make", "A single, specific, memorable claim replaced a confusing multi-claim message", "It increased manufacturing speed", "It eliminated the need for marketing"], correctIndex: 1, explanation: "Focus and specificity made the brand instantly more memorable and differentiated." },
    ],
    takeaways: ["Positioning answers 'why you, instead of any alternative, for this need?'", "Effective positioning is simple, specific, and hard to copy credibly.", "Claiming too many attributes at once dilutes and confuses your message.", "Use the positioning template to craft a clear one-sentence claim."],
    rememberThis: "If your positioning could apply to any competitor too, it isn't really positioning.",
  },
  {
    id: "day-33", day: 33, phaseId: "marketing", slug: "marketing-funnel",
    title: "Marketing Funnel",
    objective: "Understand the customer journey stages from first awareness to loyal advocacy.",
    concept: "The marketing funnel maps the stages a customer passes through: Awareness (first hears about you) → Interest (wants to know more) → Consideration (compares options) → Conversion (buys) → Retention (keeps using/buying) → Advocacy (recommends to others).",
    simpleExplanation: "Different marketing activities work at different funnel stages — a flashy ad might create awareness, but it won't retain a customer; that requires great product experience and support.",
    analogy: "The funnel is like courting someone — you don't propose marriage (conversion) on the first date (awareness); each stage requires a different kind of effort and trust-building.",
    businessExample: "A SaaS company might use social media ads for Awareness, a free webinar for Interest, a comparison page for Consideration, a free trial for Conversion, onboarding emails for Retention, and a referral program for Advocacy.",
    indiaExample: "Swiggy uses app install ads for Awareness, discount codes for first orders to drive Conversion, personalised recommendations for Retention, and refer-a-friend credits for Advocacy.",
    mnemonic: { label: "AICCRA (Funnel Stages)", breakdown: ["A = Awareness", "I = Interest", "C = Consideration", "C = Conversion", "R = Retention", "A = Advocacy"] },
    commonMistake: "Pouring all marketing budget into Awareness (top of funnel) while ignoring Retention and Advocacy — this leads to a 'leaky bucket' where you constantly need new customers because old ones don't stick around.",
    exercise: { prompt: "For a gym membership business, name one specific marketing activity for each funnel stage: Awareness, Consideration, Conversion, Retention, Advocacy.", answer: "Example: Awareness = local Instagram ads. Consideration = a free trial class. Conversion = a limited-time sign-up discount. Retention = personalised workout check-ins. Advocacy = a 'bring a friend free' referral offer." },
    caseStudy: "A startup spent 90% of its marketing budget on paid ads driving new sign-ups (Awareness/Conversion) but had no onboarding emails or retention strategy. Despite strong top-of-funnel numbers, revenue stayed flat because customers churned quickly — redirecting even 20% of budget toward retention efforts reversed the stagnation.",
    founderQuestion: "Which funnel stage is currently your weakest, and what is ONE specific action you could take this week to strengthen it?",
    quiz: [
      { id: "d33q1", question: "What is the correct order of the marketing funnel stages?", options: ["Conversion, Awareness, Retention, Interest", "Awareness, Interest, Consideration, Conversion, Retention, Advocacy", "Retention, Advocacy, Awareness, Interest", "Interest, Awareness, Conversion, Consideration"], correctIndex: 1, explanation: "This is the standard sequence a customer moves through." },
      { id: "d33q2", question: "What problem occurs when all marketing budget goes only to Awareness/Conversion?", options: ["Too many new customers", "A 'leaky bucket' effect where churned customers require constant costly replacement", "Prices become too low", "Branding becomes too strong"], correctIndex: 1, explanation: "Ignoring retention means constantly needing new customers to replace churned ones." },
      { id: "d33q3", question: "What fixed the startup's stagnant revenue in the case study?", options: ["More paid ads", "Redirecting budget toward retention efforts", "Lowering prices further", "Firing the marketing team"], correctIndex: 1, explanation: "Investing in retention addressed the root cause of the stagnation — churn." },
    ],
    takeaways: ["The funnel: Awareness → Interest → Consideration → Conversion → Retention → Advocacy.", "Different marketing tactics work at different funnel stages.", "Over-investing in Awareness while ignoring Retention creates a 'leaky bucket.'", "Advocacy (referrals) is often the cheapest, highest-trust acquisition channel."],
    rememberThis: "Winning the funnel means not just filling the top — it means keeping the bottom from leaking.",
  },
  {
    id: "day-34", day: 34, phaseId: "marketing", slug: "digital-marketing",
    title: "Digital Marketing",
    objective: "Get a practical overview of the main digital marketing channels and when to use each.",
    concept: "Digital marketing includes SEO (organic search visibility), paid ads (search/social), content marketing (blogs, videos), email marketing, social media, and influencer marketing — each with different cost, speed, and trust profiles.",
    simpleExplanation: "SEO is slow but cheap and builds long-term trust. Paid ads are fast but cost money continuously. Content marketing builds authority over time. Email is cheap and great for retention. Influencers borrow trust from an existing audience.",
    analogy: "Think of digital channels like different fishing methods: paid ads are like renting a trawler (fast, costly, immediate), SEO is like planting a fish farm (slow, but eventually self-sustaining).",
    businessExample: "HubSpot built much of its growth through content marketing (free guides, blog posts) that ranked well in search, building long-term organic traffic without constant ad spend.",
    indiaExample: "Many D2C Indian brands rely heavily on Instagram and YouTube influencer marketing to quickly build trust and reach niche, engaged audiences cost-effectively.",
    formula: { name: "Simple CAC check per channel", expression: "Channel CAC = Total spend on channel ÷ Customers acquired from that channel", workedExample: "₹50,000 spent on Instagram ads bringing in 100 customers → Channel CAC = ₹500. Compare this across channels to see which is most cost-effective." },
    commonMistake: "Using the same channel for every goal — e.g. relying only on paid ads for a product that actually needs SEO's long-term trust-building, or using slow-to-build SEO when you need fast initial traction.",
    exercise: { prompt: "A new local bakery needs customers THIS WEEK. A B2B software company wants sustainable organic growth over 2 years. Which primary digital channel would you recommend for each, and why?", answer: "Bakery: local paid social ads or Google local ads (fast, immediate traffic). B2B software: SEO and content marketing (builds durable, compounding organic traffic over time, well-suited to long sales cycles)." },
    caseStudy: "A startup spent its entire first-year budget on paid ads, achieving fast growth but needing to keep spending to sustain it. A competitor invested the same budget into SEO-focused content; growth was slower initially, but by year two, organic traffic cost them nothing extra and compounded, giving them a much lower long-term customer acquisition cost.",
    founderQuestion: "If you had to choose only ONE digital channel to master for the next year, which would best match your product's price point, sales cycle, and urgency — and why?",
    quiz: [
      { id: "d34q1", question: "Which channel is typically slow to build but becomes cheap and self-sustaining long-term?", options: ["Paid ads", "SEO / organic content", "Influencer marketing", "Cold calling"], correctIndex: 1, explanation: "SEO takes time to rank but doesn't require continuous spend once established." },
      { id: "d34q2", question: "What is Channel CAC used to compare?", options: ["Employee salaries across departments", "Cost-effectiveness of acquiring a customer through different marketing channels", "Product pricing tiers", "Office rent"], correctIndex: 1, explanation: "It isolates the acquisition cost specific to one channel for comparison." },
      { id: "d34q3", question: "Why did the SEO-focused startup have a lower long-term CAC than the paid-ads-only competitor?", options: ["SEO is always instantly effective", "Organic traffic compounded over time without continuous spend", "They had better products", "They spent more money overall"], correctIndex: 1, explanation: "Once established, SEO traffic doesn't require ongoing spend to maintain, unlike paid ads." },
    ],
    takeaways: ["Different digital channels suit different goals: SEO (long-term/cheap), paid ads (fast/costly), content (authority), email (retention), influencers (borrowed trust).", "Use Channel CAC to compare cost-effectiveness across channels.", "Match the channel to your urgency, price point, and sales cycle.", "Diversify channels rather than relying entirely on one."],
    rememberThis: "Paid ads rent attention; SEO and content build attention you own.",
  },
  {
    id: "day-35", day: 35, phaseId: "marketing", slug: "marketing-campaign-project",
    title: "Marketing Campaign Project",
    objective: "Apply STP, branding, positioning, the funnel, and digital channels into one complete campaign plan.",
    concept: "This project combines Days 29-34 into a single applied marketing campaign plan: define your STP, write a positioning statement, map funnel-stage tactics, and choose your primary digital channels with a rough budget allocation.",
    simpleExplanation: "This is the kind of one-page marketing plan a founder would create before spending any real money on customer acquisition.",
    analogy: "Think of this like a battle plan before a military campaign — you don't move resources until you know your target, your message, and your terrain.",
    businessExample: "A campaign plan for a new plant-based protein brand: Segment = health-conscious urban millennials. Position = 'protein that doesn't taste like punishment.' Funnel = Instagram ads (Awareness) → free sample program (Consideration) → D2C website discount (Conversion) → subscription perks (Retention) → referral codes (Advocacy). Channels = Instagram ads + micro-influencers + SEO blog content on protein nutrition.",
    commonMistake: "Creating a campaign plan with no connection between the positioning statement and the actual ad messaging — every tactic should reinforce the same core position, not say something different at each stage.",
    exercise: { prompt: "Write a one-page marketing campaign plan for your own business idea: STP, positioning statement, one tactic per funnel stage, and your top 2 digital channels with reasoning.", answer: "There's no single correct answer — success means every element (STP, positioning, funnel tactics, channels) is specific, consistent, and reinforces the same core message." },
    caseStudy: "A founder built a full campaign plan for a kids' educational toy brand: targeting urban parents of children aged 4-8, positioned as 'screen-free learning that feels like play.' Every funnel-stage tactic (ads, parenting blog content, in-app trial offers, loyalty rewards, parent referral codes) consistently reinforced this exact message — resulting in a coherent, recognisable brand from day one rather than disjointed messaging across channels.",
    founderQuestion: "Looking at your own completed campaign plan, does every single tactic reinforce the SAME positioning message, or do some contradict each other?",
    quiz: [
      { id: "d35q1", question: "What should a complete marketing campaign plan include?", options: ["Only a budget number", "STP, positioning, funnel-stage tactics, and channel choices", "Only a logo design", "Only competitor names"], correctIndex: 1, explanation: "A complete plan connects targeting, message, funnel tactics, and channels coherently." },
      { id: "d35q2", question: "What mistake should be avoided when building a campaign plan?", options: ["Using more than one channel", "Having tactics that say something inconsistent with your core positioning", "Including a budget", "Targeting a specific segment"], correctIndex: 1, explanation: "Every tactic should reinforce the same consistent position, not contradict it." },
      { id: "d35q3", question: "What made the kids' toy brand's campaign coherent?", options: ["They used the most channels possible", "Every funnel-stage tactic reinforced the same 'screen-free learning that feels like play' message", "They spent the most money", "They copied a competitor exactly"], correctIndex: 1, explanation: "Consistency across every touchpoint created a recognisable, coherent brand experience." },
    ],
    takeaways: ["A full campaign plan combines STP, positioning, funnel tactics, and channel selection.", "Every tactic across every funnel stage should reinforce the same core position.", "This is the one-page plan a serious founder creates before spending acquisition budget.", "Coherence across channels builds a stronger, more recognisable brand than disjointed messaging."],
    rememberThis: "A great campaign says the same true thing, consistently, everywhere a customer looks.",
  },
];
