import type { Lesson } from "../types";

export const phase06Lessons: Lesson[] = [
  {
    id: "day-36", day: 36, phaseId: "sales", slug: "sales-fundamentals",
    title: "Sales Fundamentals",
    objective: "Understand what sales really is and how it differs from (but connects to) marketing.",
    concept: "Sales is the direct, often one-on-one process of helping a specific prospect understand why your product solves their problem and guiding them to a purchase decision. Marketing creates demand at scale; sales converts individual interest into a committed customer.",
    simpleExplanation: "Marketing opens the door and gets someone curious; sales walks them through the door and helps them decide to buy.",
    analogy: "Marketing is a billboard advertising a restaurant; sales is the waiter who answers your questions, recommends dishes, and makes you comfortable enough to order.",
    businessExample: "Enterprise software companies (like Salesforce) rely heavily on sales teams who have long, consultative conversations with large clients — marketing alone can't close a ₹50 lakh annual contract.",
    indiaExample: "Insurance agents in India often rely on relationship-based, one-on-one sales conversations to build the trust needed for customers to commit to long-term financial products.",
    commonMistake: "Believing a great product sells itself without any sales effort — even excellent products often need a human (or well-designed self-serve flow) to overcome doubt, answer objections, and build confidence to buy.",
    exercise: { prompt: "Think of a big purchase you made (car, laptop, course). What role did a salesperson (or sales-like content, like reviews/demos) play in your final decision?", answer: "Example: Buying a laptop — marketing (ads) made me aware of the brand, but a salesperson's demo and answers to my specific questions about battery life and warranty were what actually convinced me to buy that specific model." },
    caseStudy: "A B2B SaaS startup assumed their website's self-serve sign-up would be enough. Conversion was low. After adding a simple 'book a demo call' option, conversion jumped — many prospects just needed someone to answer 2-3 specific questions before committing, which marketing content alone couldn't do.",
    founderQuestion: "At what point in your customer's buying journey do they most need a human conversation rather than more marketing content — and do you currently provide that?",
    quiz: [
      { id: "d36q1", question: "What is the key difference between marketing and sales?", options: ["They are identical", "Marketing creates demand at scale; sales converts individual interest into a committed customer", "Sales is only for B2B", "Marketing always costs more"], correctIndex: 1, explanation: "Marketing operates broadly; sales operates one-on-one to close specific deals." },
      { id: "d36q2", question: "Why might even a great product still need sales effort?", options: ["Great products never need marketing", "Customers often need a human (or guided flow) to overcome doubt and objections", "Sales is required by law", "Good products are always too expensive"], correctIndex: 1, explanation: "Doubt and specific questions often require direct human guidance to resolve." },
      { id: "d36q3", question: "What fixed the B2B SaaS startup's low conversion?", options: ["Lowering the price", "Adding a 'book a demo call' option to answer specific questions directly", "Changing the website colours", "Removing the sign-up form"], correctIndex: 1, explanation: "A direct conversation resolved specific doubts that marketing content couldn't address." },
    ],
    takeaways: ["Sales converts individual interest into committed customers, one conversation at a time.", "Marketing creates awareness at scale; sales closes specific deals.", "Even great products often need a human touchpoint to resolve doubt.", "Identify where in your funnel customers need a real conversation, not just more content."],
    rememberThis: "Marketing opens the door; sales walks the customer through it.",
  },
  {
    id: "day-37", day: 37, phaseId: "sales", slug: "lead-generation",
    title: "Lead Generation",
    objective: "Learn how businesses identify and capture potential customers (leads) before converting them.",
    concept: "A lead is a person or company that has shown some interest in your product (e.g. filled a form, downloaded content, started a free trial). Lead generation is the process of attracting and capturing this interest so a sales process can begin.",
    simpleExplanation: "You can't sell to someone you haven't identified yet. Lead generation turns anonymous website visitors or cold contacts into identifiable, contactable prospects.",
    analogy: "Lead generation is like a fishing net cast into a lake — it doesn't catch every fish, but it identifies which ones are nearby and interested enough to bite.",
    businessExample: "A B2B software company might offer a free downloadable guide in exchange for an email address — turning an anonymous visitor into an identifiable, follow-up-able lead.",
    indiaExample: "Real estate developers in India commonly use free site-visit offers or brochure downloads (collecting phone numbers) as lead generation tactics before their sales teams follow up with calls.",
    formula: { name: "Lead-to-Customer Progression", expression: "Lead → Prospect → Qualified Lead → Opportunity → Customer", workedExample: "1,000 website visitors fill a form (Leads) → 300 respond to a follow-up call (Prospects) → 100 have budget and real need (Qualified Leads) → 40 are in active negotiation (Opportunities) → 15 sign a contract (Customers)." },
    commonMistake: "Treating every lead as equally valuable and spending equal sales time on all of them, instead of quickly identifying which leads are worth pursuing (qualification, covered on Day 39).",
    exercise: { prompt: "List 2 lead generation tactics appropriate for a B2B accounting software company, and 2 appropriate for a D2C skincare brand.", answer: "B2B: a free 'tax-saving checklist' download (email capture), a LinkedIn webinar on GST filing. D2C: an Instagram giveaway requiring email sign-up, a quiz ('find your skin type') that captures contact details for personalised recommendations." },
    caseStudy: "A startup selling office furniture to companies struggled with cold outreach. After creating a simple 'office space planning calculator' tool requiring an email to see results, they generated hundreds of qualified leads from companies actively planning office changes — far more effective than cold calling.",
    founderQuestion: "What piece of genuinely useful content or tool could you offer for free that would naturally attract exactly your ICP to give you their contact information?",
    quiz: [
      { id: "d37q1", question: "What is a 'lead'?", options: ["Any random person", "Someone who has shown some interest in your product and can be contacted", "Only a paying customer", "A company's employee"], correctIndex: 1, explanation: "A lead is an identified, contactable person showing some level of interest." },
      { id: "d37q2", question: "What is the correct lead progression sequence?", options: ["Customer → Lead → Prospect", "Lead → Prospect → Qualified Lead → Opportunity → Customer", "Opportunity → Lead → Customer", "Prospect → Customer → Lead"], correctIndex: 1, explanation: "This is the standard progression from first interest to closed sale." },
      { id: "d37q3", question: "Why did the office space calculator tool generate effective leads?", options: ["It was free advertising", "It attracted companies actively planning office changes while capturing their contact info", "It required no email", "It was a cold call script"], correctIndex: 1, explanation: "The tool self-selected genuinely interested, relevant prospects." },
    ],
    takeaways: ["A lead is an identified person/company showing some interest in your product.", "Lead generation turns anonymous interest into contactable prospects.", "The progression is: Lead → Prospect → Qualified Lead → Opportunity → Customer.", "Useful free content/tools are effective ways to attract genuinely relevant leads."],
    rememberThis: "You can't sell to someone you can't identify — lead generation makes the invisible visible.",
  },
  {
    id: "day-38", day: 38, phaseId: "sales", slug: "sales-funnel",
    title: "Sales Funnel",
    objective: "Understand the stages a lead moves through on the way to becoming a paying customer.",
    concept: "The sales funnel visualises how many leads enter at the top and how many convert at each subsequent stage, narrowing down to actual customers. Tracking conversion rates between stages reveals exactly where prospects are lost.",
    simpleExplanation: "Not every lead becomes a customer — the funnel shows you exactly where and how much you're losing at each stage, so you know where to focus improvement efforts.",
    analogy: "A sales funnel is like a funnel for pouring liquid — wide at the top (many leads), narrow at the bottom (few actual customers), with some liquid inevitably spilling out along the sides at each stage.",
    businessExample: "A software company might see: 1,000 leads → 400 book a demo → 150 get a proposal → 50 negotiate terms → 20 sign — each step shows a conversion rate that can be individually improved.",
    indiaExample: "An ed-tech company selling test-prep courses might track: 5,000 app downloads → 1,000 complete a free diagnostic test → 300 attend a counselling call → 80 enroll — revealing the diagnostic-to-counselling step as the biggest drop-off to fix.",
    formula: { name: "Funnel Conversion Rate", expression: "Stage Conversion % = (Number advancing to next stage ÷ Number entering this stage) × 100", workedExample: "400 demo bookings from 1,000 leads → Conversion = (400 ÷ 1,000) × 100 = 40%. If only 150 of those 400 get a proposal, that stage's conversion = (150 ÷ 400) × 100 = 37.5%." },
    commonMistake: "Focusing all improvement effort on the top of the funnel (more leads) when the real problem is a weak conversion rate at a specific middle stage — more leads into a broken funnel just wastes more effort.",
    exercise: { prompt: "A gym has: 500 free trial sign-ups → 200 attend a trial class → 40 purchase a membership. Calculate the conversion rate at each stage and identify the weakest stage.", answer: "Trial attendance rate = (200÷500)×100 = 40%. Purchase rate = (40÷200)×100 = 20%. The weakest stage is trial-attendance-to-purchase (20%), suggesting the in-person trial experience or follow-up sales conversation needs improvement." },
    caseStudy: "An insurance company noticed overall sales were low and assumed they needed more leads. After mapping their funnel, they discovered their lead-to-demo conversion was actually strong (60%) but their demo-to-close rate was weak (10%) — the real problem was their sales pitch during the demo, not lead volume. Fixing the pitch script doubled closes without spending more on lead generation.",
    founderQuestion: "If you mapped your own sales funnel stage by stage, which specific stage do you suspect has the weakest conversion rate — and why haven't you fixed it yet?",
    quiz: [
      { id: "d38q1", question: "What does a sales funnel help you identify?", options: ["Only total revenue", "Exactly where and how much you're losing prospects at each stage", "Employee salaries", "Office location"], correctIndex: 1, explanation: "Stage-by-stage tracking reveals specific conversion bottlenecks." },
      { id: "d38q2", question: "Why is adding more leads not always the right fix for low sales?", options: ["It never helps", "If a specific middle stage has weak conversion, more leads just enter a broken funnel", "Leads are always too expensive", "More leads always fix funnels"], correctIndex: 1, explanation: "Fixing the actual bottleneck stage is more effective than just adding volume at the top." },
      { id: "d38q3", question: "What did the insurance company discover after mapping their funnel?", options: ["They needed more leads", "Their demo-to-close conversion was the weak stage, not lead volume", "Their pricing was too low", "Nothing was wrong"], correctIndex: 1, explanation: "Pinpointing the actual weak stage (demo pitch) let them fix the real problem." },
    ],
    takeaways: ["A sales funnel shows conversion rates at each stage from lead to customer.", "Funnel Conversion % = (advancing ÷ entering) × 100, calculated per stage.", "Identify and fix the weakest specific stage rather than just adding more leads.", "Mapping the funnel often reveals surprising, non-obvious bottlenecks."],
    rememberThis: "Don't pour more water into a leaky funnel — find and fix the leak first.",
  },
  {
    id: "day-39", day: 39, phaseId: "sales", slug: "qualification",
    title: "Qualification (BANT)",
    objective: "Learn to quickly identify which leads are actually worth your sales time using the BANT framework.",
    concept: "Qualification is the process of determining whether a lead has real potential to become a customer soon, using criteria like Budget, Authority, Need, and Timeline (BANT) — helping sales teams focus energy on the most promising opportunities.",
    simpleExplanation: "Not every interested lead can actually buy right now. BANT quickly filters out leads who lack money, decision power, a real need, or a near-term reason to act.",
    analogy: "Qualification is like a bouncer checking IDs at a club entrance — it's not about rejecting people, it's about quickly confirming who's actually eligible to come in right now.",
    businessExample: "A B2B software salesperson might ask: 'Do you have budget allocated this quarter? (Budget) Are you the person who approves this purchase? (Authority) What problem are you trying to solve? (Need) When do you need this live by? (Timeline)'",
    indiaExample: "Real estate sales teams in India commonly qualify leads early by asking about budget range and loan pre-approval status before investing time in detailed property tours.",
    mnemonic: { label: "BANT", breakdown: ["B = Budget (can they afford it?)", "A = Authority (can they decide, or do they need approval?)", "N = Need (do they have a real, specific problem?)", "T = Timeline (do they need a solution soon, or just browsing?)"] },
    commonMistake: "Spending equal time on every lead regardless of BANT signals — a lead with no budget and no timeline, however enthusiastic, will rarely convert soon and shouldn't consume the same effort as a strongly qualified lead.",
    exercise: { prompt: "A lead says: 'I love this product, but I'd need my manager's approval, we have no budget allocated this year, and we're not in a rush.' Using BANT, should this lead be prioritised now? Why?", answer: "No — this lead fails Budget (none allocated) and Timeline (no urgency), and has weak Authority (needs manager approval). It should be nurtured with low-effort follow-up (e.g. periodic emails) rather than prioritised for immediate, intensive sales effort." },
    caseStudy: "A sales team at a startup was spending 70% of their time on leads who 'loved the demo' but kept delaying decisions. After applying BANT rigorously, they realised most of these leads had no real budget allocated. Refocusing effort on leads with confirmed budget and urgent timelines doubled their close rate within one quarter.",
    founderQuestion: "Of your current leads, which ones would fail a strict BANT check — and are you still spending disproportionate time on them anyway?",
    quiz: [
      { id: "d39q1", question: "What does the 'N' in BANT stand for?", options: ["Network", "Need", "Negotiation", "Number"], correctIndex: 1, explanation: "Need checks whether the lead has a real, specific problem your product solves." },
      { id: "d39q2", question: "Why is qualification important before investing sales time?", options: ["It's legally required", "It focuses limited sales effort on leads most likely to convert soon", "It eliminates the need for a sales team", "It guarantees a sale"], correctIndex: 1, explanation: "Qualification helps prioritise effort toward the most promising opportunities." },
      { id: "d39q3", question: "What happened after the startup applied BANT rigorously?", options: ["They lost all their leads", "Refocusing on properly qualified leads doubled their close rate", "Nothing changed", "They had to hire more salespeople"], correctIndex: 1, explanation: "Focusing effort on well-qualified leads improved conversion efficiency." },
    ],
    takeaways: ["BANT = Budget, Authority, Need, Timeline — a framework for qualifying leads.", "Not every enthusiastic lead is ready or able to buy soon.", "Prioritise sales effort toward leads that pass most or all BANT criteria.", "Rigorous qualification can significantly improve close rates without needing more leads."],
    rememberThis: "Enthusiasm isn't qualification — check Budget, Authority, Need, and Timeline before investing real sales time.",
  },
  {
    id: "day-40", day: 40, phaseId: "sales", slug: "negotiation",
    title: "Negotiation",
    objective: "Learn core principles of fair, effective business negotiation.",
    concept: "Negotiation is the process of reaching a mutually acceptable agreement between a buyer and seller, balancing price, terms, and value. Good negotiation focuses on understanding the other side's real priorities, not just pushing your own position.",
    simpleExplanation: "Negotiation isn't about 'winning' at the other side's expense — the best deals happen when both sides feel they got something valuable, increasing the chance of a lasting relationship.",
    analogy: "Negotiation is like splitting a pizza when both people are hungry — if one side eats it all, the other walks away angry and won't share future pizzas (deals) with you.",
    businessExample: "A supplier negotiating with a large retailer might trade a lower price for a longer-term, higher-volume contract — both sides get something valuable (retailer gets lower cost, supplier gets guaranteed volume).",
    indiaExample: "In Indian B2B deals, payment terms (e.g. 30 vs. 60-day credit) are often negotiated as heavily as price itself, since cash flow timing matters enormously to small suppliers.",
    commonMistake: "Focusing only on price as the single negotiation variable, when terms like payment timing, contract length, volume commitments, or exclusivity can often create more flexible, mutually beneficial trade-offs.",
    exercise: { prompt: "A client wants a 20% price discount you can't afford to give. Name two non-price concessions you could offer instead that might satisfy them.", answer: "Example: Offer a longer payment term (60 days instead of 30) to help their cash flow, or offer a value-add (free onboarding support) instead of a straight price cut — preserving your margin while still giving them something valuable." },
    caseStudy: "A startup selling to a large enterprise client faced pressure for a steep discount. Instead of cutting price, the founder offered a 12-month contract (instead of month-to-month) in exchange for keeping the original price — the client valued budget predictability more than the discount, and the startup secured guaranteed revenue instead of losing margin.",
    founderQuestion: "In your next negotiation, what non-price value could you offer that costs you little but might matter a lot to the other side?",
    quiz: [
      { id: "d40q1", question: "What is the goal of good negotiation?", options: ["Winning at any cost to the other side", "Reaching a mutually acceptable agreement where both sides gain value", "Avoiding any compromise", "Always giving the biggest discount possible"], correctIndex: 1, explanation: "Sustainable deals are built on mutual value, not one-sided wins." },
      { id: "d40q2", question: "Besides price, what else is commonly negotiated in B2B deals?", options: ["Nothing else matters", "Payment terms, contract length, and volume commitments", "Only the company logo", "Office location"], correctIndex: 1, explanation: "Terms beyond price often provide flexible ways to reach mutual value." },
      { id: "d40q3", question: "How did the startup satisfy the enterprise client without cutting price?", options: ["They refused to negotiate at all", "They offered a longer contract term in exchange for keeping the original price", "They gave a bigger discount", "They cancelled the deal"], correctIndex: 1, explanation: "Trading contract length for price preserved margin while giving the client something they valued (predictability)." },
    ],
    takeaways: ["Good negotiation aims for mutual value, not one-sided winning.", "Price is only one of many negotiable variables — terms matter too.", "Understand what the other side truly values before conceding on price.", "Non-price concessions can preserve margin while still satisfying the other party."],
    rememberThis: "The best negotiations leave both sides feeling they got something valuable, not just one side winning.",
  },
  {
    id: "day-41", day: 41, phaseId: "sales", slug: "closing",
    title: "Closing",
    objective: "Learn how to confidently guide a qualified, interested prospect to a final purchase decision.",
    concept: "Closing is the final step of the sales process — asking directly for the commitment once objections are addressed and value is clear. Many deals are lost not because the product was wrong, but because no one ever directly asked for the sale.",
    simpleExplanation: "After doing all the work of discovery, qualification, and negotiation, closing simply means clearly and confidently asking the prospect to commit — many salespeople hesitate here out of fear of rejection.",
    analogy: "Closing is like asking someone out after a great series of conversations — all the groundwork is wasted if you never actually ask.",
    businessExample: "A classic effective close is the 'next steps' close: 'Based on everything we've discussed, it sounds like this solves your problem well — shall we get the contract signed this week?' — direct, confident, and based on established value.",
    indiaExample: "In Indian retail and B2B sales, a common closing tactic is offering a small time-bound incentive ('this price is valid only till end of month') to create a natural reason for the prospect to decide now rather than indefinitely delaying.",
    commonMistake: "Over-explaining and continuing to pitch even after the prospect has shown clear buying signals — sometimes salespeople talk themselves out of a sale that was already won by introducing new doubts.",
    exercise: { prompt: "A prospect says: 'This all sounds great, I just need to think about it.' Write one direct, non-pushy follow-up question to understand their real hesitation.", answer: "Example: 'That's completely understandable — can I ask what specifically you'd want to think through? I want to make sure I've addressed everything clearly before you decide.'" },
    caseStudy: "A sales rep noticed her close rate was low despite prospects seeming genuinely interested throughout the call. After reviewing recorded calls, she realised she never actually asked for the sale directly — she just described the product and waited. Adding one clear, confident closing question at the end of every call ('shall we move forward with this today?') significantly improved her close rate.",
    founderQuestion: "In your last 5 sales conversations, did you ever clearly and directly ask for the sale — or did you just hope the prospect would ask to buy on their own?",
    quiz: [
      { id: "d41q1", question: "What is 'closing' in a sales process?", options: ["Ending the relationship with a customer", "Directly asking the prospect to commit to the purchase", "Lowering the price", "Sending a thank-you email"], correctIndex: 1, explanation: "Closing is the explicit ask for commitment after value has been established." },
      { id: "d41q2", question: "Why do many deals fail to close even when the prospect seems interested?", options: ["The product is always bad", "The salesperson never directly asked for the commitment", "Prices are always too high", "Prospects always say no eventually"], correctIndex: 1, explanation: "A common failure point is simply never making the direct ask." },
      { id: "d41q3", question: "What improved the sales rep's close rate in the case study?", options: ["Lowering prices", "Adding a clear, direct closing question at the end of every call", "Talking more during the pitch", "Avoiding all questions"], correctIndex: 1, explanation: "Directly asking for commitment, rather than waiting passively, drove the improvement." },
    ],
    takeaways: ["Closing means directly and confidently asking the prospect to commit.", "Many lost deals fail simply because no direct ask was ever made.", "Avoid over-explaining after clear buying signals appear.", "Use direct, non-pushy closing questions to uncover and resolve remaining hesitation."],
    rememberThis: "Groundwork without a direct ask is a sale left on the table.",
  },
  {
    id: "day-42", day: 42, phaseId: "sales", slug: "sales-case-study-day",
    title: "Sales Case Study Day",
    objective: "Apply the full sales process — lead gen, funnel, qualification, negotiation, closing — to a realistic scenario, with core metrics.",
    concept: "This review day connects Days 36-41 using key sales metrics: CAC (cost to acquire a customer), conversion rate, average order value, and sales cycle length — the numbers that reveal whether a sales process is actually healthy.",
    simpleExplanation: "A sales process isn't just about technique — it's measurable. Tracking CAC, conversion rate, average order value, and cycle length tells you exactly where to improve.",
    formula: { name: "Key Sales Metrics", expression: "Conversion Rate % = (Customers ÷ Leads) × 100\nCAC = Total Sales + Marketing Cost ÷ New Customers\nAvg Order Value = Total Revenue ÷ Number of Orders", workedExample: "1,000 leads → 50 customers → Conversion Rate = 5%. ₹5,00,000 spent on sales+marketing for those 50 customers → CAC = ₹10,000. ₹25,00,000 total revenue from 50 customers → Avg Order Value = ₹50,000." },
    analogy: "Sales metrics are like a car's dashboard — speed (conversion rate), fuel efficiency (CAC), and distance per trip (average order value) tell you exactly how the engine is really performing.",
    businessExample: "A B2B software company tracking these metrics might discover their CAC (₹15,000) is higher than their first-year customer value (₹12,000) — a red flag requiring immediate attention to either reduce CAC or increase deal size/retention.",
    indiaExample: "Many Indian D2C brands closely track CAC vs. average order value in their first 100 days, since overspending on paid ads relative to order value can quickly burn through limited early-stage cash.",
    commonMistake: "Tracking vanity metrics (total leads, website visits) while ignoring the metrics that actually reveal sales health: conversion rate, CAC, and whether CAC is sustainably lower than customer value.",
    exercise: { prompt: "A startup has: 2,000 leads, 80 customers, ₹8,00,000 total sales/marketing spend, ₹20,00,000 total revenue. Calculate Conversion Rate, CAC, and Average Order Value.", answer: "Conversion Rate = (80÷2,000)×100 = 4%. CAC = 8,00,000÷80 = ₹10,000. Average Order Value = 20,00,000÷80 = ₹25,000. Since Average Order Value (₹25,000) is more than double the CAC (₹10,000), the unit economics look healthy on this metric alone." },
    caseStudy: "A startup celebrated hitting 10,000 leads in a quarter, but their finance team flagged that conversion rate had actually dropped from 8% to 3% in the same period — meaning the quality of leads had declined even as quantity grew. Shifting lead generation focus back toward BANT-qualified channels restored both conversion rate and overall revenue growth.",
    founderQuestion: "If you tracked only ONE sales metric obsessively for the next quarter, would it be conversion rate, CAC, or average order value — and why is that the one that matters most for your stage right now?",
    quiz: [
      { id: "d42q1", question: "What does Conversion Rate measure in sales?", options: ["Total revenue", "The percentage of leads that become paying customers", "Employee productivity", "Office rent efficiency"], correctIndex: 1, explanation: "Conversion Rate = (Customers ÷ Leads) × 100, showing funnel effectiveness." },
      { id: "d42q2", question: "Why is tracking only total lead count potentially misleading?", options: ["Lead count is always accurate", "High lead volume can hide a declining conversion rate (lower lead quality)", "Leads don't matter at all", "It's illegal to track leads"], correctIndex: 1, explanation: "Volume without quality context can mask a worsening conversion problem." },
      { id: "d42q3", question: "What warning sign should concern a startup about its CAC?", options: ["CAC being lower than customer value", "CAC being higher than the value a customer generates", "CAC being a round number", "CAC decreasing over time"], correctIndex: 1, explanation: "If CAC exceeds customer value, the business loses money on every new customer acquired." },
    ],
    takeaways: ["Key sales metrics: Conversion Rate, CAC, and Average Order Value.", "Vanity metrics (raw lead count) can hide real problems like declining conversion quality.", "CAC should be meaningfully lower than the value a customer generates.", "Combine process skills (qualification, negotiation, closing) with metric tracking for a healthy sales engine."],
    rememberThis: "More leads isn't success if conversion quality is quietly falling — always check the ratio, not just the count.",
  },
];
