import type { Lesson } from "../types";

export const phase03Lessons: Lesson[] = [
  {
    id: "day-15", day: 15, phaseId: "customer", slug: "customer-discovery",
    title: "Customer Discovery",
    objective: "Learn how to talk to potential customers to uncover real needs, not just confirm your own assumptions.",
    concept: "Customer discovery is the structured process of interviewing real potential customers to understand their problems, habits, and willingness to pay — before building anything.",
    simpleExplanation: "Instead of pitching your idea and asking 'do you like it?', good discovery asks about their PAST behaviour and pain, which is far more honest than hypothetical future opinions.",
    analogy: "It's like a doctor diagnosing before prescribing — you ask about symptoms first, you don't hand out medicine before understanding what's wrong.",
    businessExample: "Airbnb's founders personally interviewed early hosts and guests to understand trust concerns before building trust-and-safety features into the platform.",
    indiaExample: "Urban Company's founders spent time with household service workers (plumbers, electricians) to understand income and trust issues before designing their vetting and training programs.",
    commonMistake: "Asking leading questions like 'would you use an app that does X?' — people say yes to be polite. Better: 'tell me about the last time you faced this problem — what did you do?'",
    exercise: { prompt: "Write 3 customer discovery questions for someone who might use a budgeting app, WITHOUT mentioning your app at all.", answer: "Example: 'How do you currently track your monthly spending?' 'Tell me about a time you were surprised by how much you spent.' 'What tools have you tried before, and why did you stop using them?'" },
    caseStudy: "A founder planning a meal-kit service interviewed 30 working parents instead of surveying them. She discovered the real pain wasn't 'cooking time' (her assumption) but 'decision fatigue about what to cook' — a subtly different problem that reshaped her entire product.",
    founderQuestion: "If you interviewed 10 potential customers this week without mentioning your idea at all, what questions would reveal their real pain fastest?",
    quiz: [
      { id: "d15q1", question: "Why are past-behaviour questions better than hypothetical questions in customer discovery?", options: ["They take less time", "Past behaviour is factual; hypothetical answers are often overly polite guesses", "They are required by law", "They're easier to analyse with software"], correctIndex: 1, explanation: "People's actual past actions are more reliable evidence than speculative future opinions." },
      { id: "d15q2", question: "What is a leading question to avoid in customer interviews?", options: ["'Tell me about your last experience with this problem'", "'Would you use an app that does X?'", "'What have you tried before?'", "'Why did you stop using that tool?'"], correctIndex: 1, explanation: "This invites a polite 'yes' rather than real insight." },
      { id: "d15q3", question: "What did the meal-kit founder discover through discovery interviews?", options: ["Parents wanted more recipes", "The real pain was decision fatigue, not cooking time", "Parents didn't want to cook at all", "Price was the only issue"], correctIndex: 1, explanation: "Interviews revealed a different, more precise problem than her original assumption." },
    ],
    takeaways: ["Customer discovery uncovers real needs through structured interviews.", "Ask about past behaviour, not hypothetical future preferences.", "Avoid leading questions that invite polite agreement.", "Discovery often reshapes your understanding of the 'real' problem."],
    rememberThis: "Ask about the past, not the hypothetical future — people lie less about what they've already done.",
  },
  {
    id: "day-16", day: 16, phaseId: "customer", slug: "icp",
    title: "ICP (Ideal Customer Profile)",
    objective: "Define precisely who your best-fit customer is, so you can focus resources effectively.",
    concept: "An Ideal Customer Profile (ICP) describes the specific type of customer who gets the most value from your product and is most likely to pay, stay, and refer others — the customer you should chase first.",
    simpleExplanation: "Not all customers are equal. Some are a perfect fit (high value, low effort to serve); others are a poor fit (low value, high effort, frequent complaints). ICP helps you focus on the former.",
    analogy: "An ICP is like a dating profile for your business — it defines exactly who you're looking for, so you don't waste time chasing the wrong matches.",
    businessExample: "A B2B accounting software company might define its ICP as: 'Small retail businesses in India with 5-50 employees, currently using Excel, with ₹50 lakh - ₹5 crore annual revenue.'",
    indiaExample: "Zoho's ICP for many of its products is small and mid-sized businesses (SMBs) who need affordable, all-in-one software but can't afford expensive enterprise tools like Salesforce.",
    commonMistake: "Trying to serve 'everyone' because it feels like more potential customers. In reality, unfocused targeting wastes marketing spend and leads to a mediocre product that fits nobody perfectly.",
    exercise: { prompt: "For a premium home-cleaning service, write a one-paragraph ICP including income level, location type, household size, and pain point.", answer: "Example ICP: Dual-income urban households earning ₹15 lakh+ annually, living in apartments in metro cities, with both partners working full-time, who value their limited weekend time more than the cost of professional cleaning." },
    caseStudy: "A SaaS startup initially marketed to 'any small business.' After 6 months of scattered, low-converting sales calls, they analysed their best customers and found a pattern: fast-growing e-commerce stores with 10-30 employees converted 5x better than others. Narrowing their ICP to exactly this group tripled their sales efficiency.",
    founderQuestion: "If you could only sell to one very specific type of customer for the next year, who would convert fastest and stay longest — and why?",
    quiz: [
      { id: "d16q1", question: "What is an Ideal Customer Profile (ICP)?", options: ["A list of all possible customers", "A description of the customer type that gets the most value and is easiest to serve profitably", "A legal document", "A pricing plan"], correctIndex: 1, explanation: "ICP focuses resources on the best-fit customer segment, not everyone." },
      { id: "d16q2", question: "Why is trying to serve 'everyone' often a mistake for early-stage businesses?", options: ["It's illegal", "It spreads resources thin and often results in a mediocre fit for all", "It increases costs to zero", "Everyone always wants the same thing"], correctIndex: 1, explanation: "Unfocused targeting dilutes marketing and product efforts, satisfying no one fully." },
      { id: "d16q3", question: "How did the SaaS startup improve its sales efficiency?", options: ["By lowering prices for everyone", "By narrowing its ICP to the best-converting customer segment", "By hiring more salespeople", "By adding more product features"], correctIndex: 1, explanation: "Focusing on the proven best-fit segment (fast-growing e-commerce stores) tripled efficiency." },
    ],
    takeaways: ["ICP defines your best-fit, most profitable customer type.", "Focusing on ICP beats trying to serve everyone.", "Analyse your best existing customers to refine your ICP over time.", "A precise ICP improves marketing efficiency and sales conversion."],
    rememberThis: "ICP = the customer you'd clone a thousand times if you could.",
  },
  {
    id: "day-17", day: 17, phaseId: "customer", slug: "buyer-persona",
    title: "Buyer Persona",
    objective: "Build a detailed, human picture of your target customer to guide product and marketing decisions.",
    concept: "A buyer persona is a semi-fictional, detailed profile representing a segment of your customers — including their goals, frustrations, daily habits, and decision-making triggers — used to make product and marketing choices feel grounded in a real human, not an abstraction.",
    simpleExplanation: "While ICP defines WHO to target at a business/demographic level, a persona adds personality and context — giving that customer a name, daily routine, and emotional motivations.",
    analogy: "ICP is the job description; the persona is the actual person you'd hire — with a name, habits, and personality.",
    businessExample: "A fitness app might create 'Busy Priya, 29, marketing manager, wants to work out but has unpredictable work hours, gets frustrated by rigid class schedules, prefers short effective home workouts.'",
    indiaExample: "Many Indian fintech apps build personas like 'First-time Investor Raj, 24, works in IT, scared of losing money, wants simple explanations before investing, influenced by finance YouTubers.'",
    commonMistake: "Creating a persona once and never updating it as real customer data comes in — personas should evolve with evidence, not stay fixed forever.",
    exercise: { prompt: "Create a one-paragraph persona (name, age, job, goal, frustration, and a quote) for a customer of a language-learning app.", answer: "Example: 'Ambitious Aditi, 26, software engineer, wants to learn Spanish for an upcoming international work transfer. Frustrated by apps that feel like a game instead of real progress. Quote: I don't have time to waste on childish lessons — I need results before my transfer date.'" },
    caseStudy: "An edtech startup building for 'students' realised their actual best-converting users were working professionals preparing for certification exams, not college students. Rebuilding their persona around 'Busy Professional Rohan, studying for 1 hour after work' completely changed their content length (shorter lessons) and marketing channels (LinkedIn instead of Instagram).",
    founderQuestion: "Can you describe your ideal customer's typical Tuesday, including their biggest frustration that day? If not, your persona may be too vague.",
    quiz: [
      { id: "d17q1", question: "How does a buyer persona differ from an ICP?", options: ["They are identical", "ICP defines business/demographic fit; persona adds human personality and context", "Personas are only for B2C", "ICP is only for startups"], correctIndex: 1, explanation: "ICP is the 'what' (fit criteria), persona is the 'who' (a human story)." },
      { id: "d17q2", question: "Why should personas be updated over time?", options: ["It's a legal requirement", "Real customer data provides more accurate insight than initial assumptions", "Personas expire after a year", "Investors require quarterly updates"], correctIndex: 1, explanation: "Personas should evolve as you learn more about actual customer behaviour." },
      { id: "d17q3", question: "What changed for the edtech startup after rebuilding their persona?", options: ["Nothing changed", "Content length and marketing channels shifted to match working professionals", "They raised prices", "They stopped using personas"], correctIndex: 1, explanation: "A more accurate persona led to shorter lessons and a shift to LinkedIn marketing." },
    ],
    takeaways: ["A persona humanises your ICP with goals, habits, and frustrations.", "Personas should be built from real research, not guesses.", "Update personas as real customer data emerges.", "A good persona should let you predict how a real customer would react to a decision."],
    rememberThis: "ICP tells you WHO to target; a persona tells you how they think and feel.",
  },
  {
    id: "day-18", day: 18, phaseId: "customer", slug: "tam-sam-som",
    title: "TAM / SAM / SOM",
    objective: "Learn to size a market realistically using the TAM/SAM/SOM funnel.",
    concept: "TAM (Total Addressable Market) is the entire possible market demand for your category globally or nationally. SAM (Serviceable Available Market) is the portion of TAM you could realistically serve given your business model, geography, and language. SOM (Serviceable Obtainable Market) is the realistic share you could capture in the near term given competition and resources.",
    simpleExplanation: "TAM = 'if everyone who could ever want this bought it.' SAM = 'the part of that I could actually reach with my current model.' SOM = 'what I can realistically win in the next 1-3 years.'",
    analogy: "TAM↓SAM↓SOM is like a funnel: TAM is the whole ocean, SAM is the bay near your boat, and SOM is the fish you can realistically catch this season.",
    businessExample: "For a yoga studio app in India: TAM = all people worldwide interested in yoga/fitness apps. SAM = Indian urban smartphone users interested in fitness. SOM = the % of that group you can realistically acquire in your target cities within 2 years given your marketing budget.",
    formula: { name: "TAM → SAM → SOM", expression: "TAM = Total possible market\nSAM = TAM × (% you can realistically serve, by geography/segment)\nSOM = SAM × (% you can realistically capture, by competition/resources)", workedExample: "TAM = 10 crore fitness app users in India. SAM (urban, smartphone, willing to pay) = 2 crore. SOM (realistic 2-year capture at 2% share) = 4 lakh users." },
    commonMistake: "Presenting only a huge TAM number (e.g. 'the global fitness market is $100 billion') without a credible SAM/SOM — investors see through this immediately as lacking real market understanding.",
    exercise: { prompt: "For a startup selling eco-friendly packaging to small bakeries in Bangalore, roughly estimate TAM (all bakeries needing packaging, nationally), SAM (bakeries in major Indian cities open to eco-friendly options), and SOM (bakeries you could realistically sign in Bangalore in year 1).", answer: "Example: TAM = all bakeries in India needing packaging (very large, broad number). SAM = bakeries in major metro cities interested in sustainable packaging (smaller, filtered by segment). SOM = bakeries in Bangalore you could realistically onboard in year 1 given a small sales team (a specific, achievable number)." },
    caseStudy: "A founder pitched investors with a TAM of '$50 billion global education market' but no SAM or SOM. Investors immediately asked, 'what can you realistically capture in 2 years?' Without an answer, the pitch lost credibility. After the pitch, the founder redid the analysis: SAM (Indian K-12 online tutoring) was far smaller, and SOM (a realistic 2-year target in 3 cities) was even smaller but far more credible and fundable.",
    founderQuestion: "What is your SOM for year 1 — a specific, defensible number, not a vague percentage of a huge global market?",
    quiz: [
      { id: "d18q1", question: "What does SAM represent in the TAM/SAM/SOM funnel?", options: ["The total global market", "The portion of TAM you can realistically serve given your model and geography", "Your exact year-1 revenue", "Your total funding needed"], correctIndex: 1, explanation: "SAM narrows TAM down to what's realistically serviceable by your specific business." },
      { id: "d18q2", question: "Why is presenting only a huge TAM number risky in a pitch?", options: ["TAM numbers are always wrong", "It lacks credibility without a realistic SAM/SOM breakdown", "Investors don't understand TAM", "TAM is illegal to mention"], correctIndex: 1, explanation: "Sophisticated investors want to see a credible path from TAM down to an achievable SOM." },
      { id: "d18q3", question: "What is SOM meant to represent?", options: ["The entire industry size", "A realistic, near-term capturable market share", "Your total addressable costs", "Your total employee count"], correctIndex: 1, explanation: "SOM is the specific, achievable market share you can realistically win soon." },
    ],
    takeaways: ["TAM = total market; SAM = realistically serviceable portion; SOM = realistically winnable share.", "Always narrow down from TAM to a credible SOM, not just a big headline number.", "SOM should be specific and defensible, not a vague percentage guess.", "Investors judge market sizing credibility by the SAM/SOM logic, not the TAM size alone."],
    rememberThis: "TAM is the ocean, SAM is your bay, SOM is this season's realistic catch.",
  },
  {
    id: "day-19", day: 19, phaseId: "customer", slug: "market-research",
    title: "Market Research",
    objective: "Learn practical methods to gather real data about customers, trends, and market size.",
    concept: "Market research combines primary research (data you collect directly — interviews, surveys, pilots) and secondary research (existing data — industry reports, government data, competitor information) to understand your market before committing resources.",
    simpleExplanation: "Primary research answers 'what does MY specific target customer think/do?' Secondary research answers 'what does the broader market/industry data already show?' Good founders use both.",
    analogy: "Secondary research is like reading a weather forecast; primary research is like stepping outside to feel if it's actually raining right now, for your exact location.",
    businessExample: "A startup entering the Indian EV charging space would combine secondary research (government EV policy reports, industry growth projections) with primary research (surveys/interviews with actual EV owners about charging pain points).",
    indiaExample: "Reports from NASSCOM, RBI, and the Ministry of MSME are commonly used as secondary research sources by Indian founders studying fintech, retail, and manufacturing sectors.",
    commonMistake: "Relying only on secondary research (reports and articles) without ever directly talking to real customers — this misses nuanced, local, and current realities that reports can't capture.",
    exercise: { prompt: "You're exploring a business idea in pet care services. Name one secondary research source and one primary research method you'd use.", answer: "Example: Secondary — an industry report on India's pet care market growth (e.g. from IMARC or Euromonitor). Primary — interviewing 15 pet owners in your target city about their current grooming/vet habits and pain points." },
    caseStudy: "A founder researching rural fintech adoption read several national reports suggesting high smartphone penetration meant high digital payment readiness. However, primary research (visiting 3 villages and talking to residents) revealed trust issues and poor network connectivity were still major blockers — insights no report had captured, which reshaped her entire go-to-market approach.",
    founderQuestion: "What is one secondary data source and one primary research method you could use THIS WEEK to validate assumptions about your market?",
    quiz: [
      { id: "d19q1", question: "What is the key difference between primary and secondary research?", options: ["Primary is always more expensive", "Primary is data you collect yourself; secondary is existing published data", "Secondary research is illegal to use", "They are the same thing"], correctIndex: 1, explanation: "Primary research is firsthand (interviews/surveys); secondary research reuses existing published data." },
      { id: "d19q2", question: "Why is relying only on secondary research risky?", options: ["Reports are always fake", "It can miss current, local, nuanced realities that only direct customer contact reveals", "It is more expensive than primary research", "It takes longer than primary research"], correctIndex: 1, explanation: "Published reports can be outdated or too broad to capture specific local realities." },
      { id: "d19q3", question: "What did the founder's primary research reveal that secondary reports missed?", options: ["High smartphone penetration", "Trust issues and poor network connectivity blocking digital payment adoption", "No interest in fintech at all", "Pricing was too low"], correctIndex: 1, explanation: "Direct village visits uncovered on-the-ground blockers that national reports didn't capture." },
    ],
    takeaways: ["Combine secondary research (existing data) with primary research (direct customer contact).", "Secondary research gives broad context; primary research gives specific, current truth.", "Government and industry reports are valuable but should never replace direct customer contact.", "Local, nuanced realities often only surface through primary research."],
    rememberThis: "Secondary research tells you what's generally true; primary research tells you what's true for YOUR customer.",
  },
  {
    id: "day-20", day: 20, phaseId: "customer", slug: "competitor-analysis",
    title: "Competitor Analysis",
    objective: "Learn to systematically study competitors to find gaps and sharpen your own positioning.",
    concept: "Competitor analysis means studying both direct competitors (solving the same problem, same way) and indirect competitors (solving the same problem, differently) to understand their strengths, weaknesses, pricing, and customer complaints — revealing where you can win.",
    simpleExplanation: "Studying competitors isn't about copying them — it's about finding what they do badly (their customer complaints) and doing that specific thing better.",
    analogy: "Competitor analysis is like studying game footage of opposing teams before a match — not to imitate them, but to learn their weak spots.",
    businessExample: "A new D2C coffee brand studying competitors might find that customers consistently complain online about stale beans from larger brands — becoming the brand known for 'always freshly roasted' directly addresses a known competitor weakness.",
    indiaExample: "When Byju's and Unacademy dominated test-prep, newer players found gaps around affordability and regional languages, positioning themselves specifically around underserved segments rather than competing head-on.",
    commonMistake: "Only looking at competitors' marketing/websites, while ignoring real customer reviews and complaints — reviews reveal the actual gaps you can exploit.",
    exercise: { prompt: "Pick a competitor in any industry you're interested in. Find 3 recurring complaints in their online reviews. How could a new entrant specifically address those complaints?", answer: "Example: If reviews of a food delivery app repeatedly mention 'late deliveries during peak hours,' a new entrant could specifically market guaranteed delivery-time windows during peak hours as their key differentiator." },
    caseStudy: "A new budget airline studying competitor reviews found 'hidden fees' was the most common complaint across the industry. They built their entire marketing campaign around 'no hidden fees, ever' — directly converting a known industry-wide weakness into their core differentiator.",
    founderQuestion: "What is the #1 complaint customers have about your closest competitor, and how specifically would you solve it better?",
    quiz: [
      { id: "d20q1", question: "What is the main purpose of competitor analysis?", options: ["To copy competitors exactly", "To find gaps and weaknesses you can exploit to differentiate", "To only track their pricing", "To file legal complaints against them"], correctIndex: 1, explanation: "The goal is identifying exploitable gaps, not imitation." },
      { id: "d20q2", question: "Why are customer reviews a valuable competitor research source?", options: ["They're always positive", "They reveal real, specific complaints and gaps you can exploit", "Reviews are legally binding", "They replace the need for your own product"], correctIndex: 1, explanation: "Reviews surface authentic pain points competitors haven't solved." },
      { id: "d20q3", question: "What did the budget airline build its marketing around?", options: ["Lowest prices only", "Luxury service", "'No hidden fees, ever' — addressing a common industry complaint", "Fastest booking app"], correctIndex: 2, explanation: "They turned a widely shared competitor weakness into their core differentiator." },
    ],
    takeaways: ["Study both direct and indirect competitors.", "Customer reviews reveal real gaps better than marketing materials.", "Use competitor weaknesses to shape your own differentiation, not imitation.", "A known industry-wide complaint can become your single biggest marketing advantage."],
    rememberThis: "Don't study competitors to copy them — study them to find what they're doing badly.",
  },
  {
    id: "day-21", day: 21, phaseId: "customer", slug: "market-validation-project",
    title: "Market Validation Project",
    objective: "Combine customer discovery, ICP, personas, market sizing, research, and competitor analysis into one applied project.",
    concept: "This project day asks you to apply Days 15-20 to a single idea: define your ICP and persona, estimate TAM/SAM/SOM, do basic primary/secondary research, and analyse at least one competitor — producing a one-page Market Validation Summary.",
    simpleExplanation: "This is the kind of document a thoughtful founder would create before approaching an investor or committing serious money — a structured, evidence-based view of the market opportunity.",
    analogy: "Think of this like a pilot's final pre-flight check before takeoff — pulling together every individual check (fuel, weather, weight, route) into one go/no-go decision.",
    businessExample: "A founder exploring a subscription box for Indian regional snacks would summarise: ICP (urban nostalgic professionals 25-40 living away from hometown), persona (Homesick Priya), TAM/SAM/SOM (national snack market → urban subscription-willing segment → realistic year-1 city targets), research findings (strong emotional pull, price sensitivity above ₹800/month), and competitor gaps (existing players too generic, not region-specific).",
    commonMistake: "Treating this as a purely academic exercise instead of using REAL data from actual interviews, reviews and estimates gathered this week.",
    exercise: { prompt: "Write a one-page Market Validation Summary for your own business idea, including: ICP, persona, TAM/SAM/SOM estimate, 2 research findings, and 1 competitor gap.", answer: "There's no single correct answer — the exercise is successful if every section is filled with specific, evidence-based reasoning rather than vague generalities." },
    caseStudy: "A founder completed this exact exercise for a tutoring marketplace idea and discovered, through her own research, that her assumed ICP (parents of school children) was actually less promising than working professionals studying for certifications — a discovery that completely reshaped her product roadmap before she wrote a single line of code.",
    founderQuestion: "After completing your Market Validation Summary, has anything about your original idea changed? What surprised you most?",
    quiz: [
      { id: "d21q1", question: "What does a Market Validation Summary combine?", options: ["Only a TAM estimate", "ICP, persona, TAM/SAM/SOM, research findings, and competitor gaps", "Only competitor pricing", "Only customer interviews"], correctIndex: 1, explanation: "It's a synthesis of every market-facing analysis from the week." },
      { id: "d21q2", question: "Why is using real data important for this exercise?", options: ["It's a legal requirement", "Evidence-based reasoning produces far more useful and credible conclusions than guesses", "Real data is always more impressive to friends", "It's optional and doesn't matter"], correctIndex: 1, explanation: "The entire value of this exercise comes from grounding it in real evidence, not assumptions." },
      { id: "d21q3", question: "What did the tutoring marketplace founder discover from her own exercise?", options: ["Her original ICP was perfect", "A different customer segment was more promising than her original assumption", "No one needed tutoring", "Pricing didn't matter at all"], correctIndex: 1, explanation: "Her research revealed working professionals were a better-fit ICP than her original assumption." },
    ],
    takeaways: ["A Market Validation Summary combines ICP, persona, TAM/SAM/SOM, research, and competitor analysis.", "This is the kind of document a serious founder prepares before committing resources.", "Use real evidence gathered this week, not guesses.", "Be ready for this exercise to change your original assumptions — that's a sign it's working."],
    rememberThis: "A great market validation summary doesn't confirm what you believed — it tests it.",
  },
];
