import type { Lesson } from "../types";

export const phase04Lessons: Lesson[] = [
  {
    id: "day-22", day: 22, phaseId: "product", slug: "product-fundamentals",
    title: "Product Fundamentals",
    objective: "Understand what a 'product' really is and the core jobs a product manager does.",
    concept: "A product is anything (physical or digital) that solves a customer's problem and delivers value in exchange for money or attention. Product management is the discipline of deciding WHAT to build and WHY, balancing customer needs, business goals, and technical feasibility.",
    simpleExplanation: "A product manager doesn't necessarily build the product themselves — they decide what gets built, in what order, and why, based on evidence.",
    analogy: "A product manager is like a film director — they don't operate every camera or write every line, but they decide the vision and make sure every department works toward the same story.",
    businessExample: "At Amazon, product managers for the 'Buy Box' feature constantly balance seller fairness, customer trust, and company revenue when deciding how products are ranked for sale.",
    indiaExample: "At Zomato, a product manager might decide whether to prioritise building a new 'live order tracking' feature or improving restaurant search — based on customer complaint data and business impact.",
    commonMistake: "Confusing product management with just 'managing a to-do list of features.' Real product management means saying NO to many good ideas to focus on the few that matter most.",
    exercise: { prompt: "List 3 features you could add to a food delivery app. For each, write one reason a product manager might say NO to building it right now.", answer: "Example: (1) In-app games — fun but doesn't address core delivery speed/trust problems. (2) Voice ordering — low near-term demand evidence. (3) Loyalty points — could be valuable, but requires solid retention data first to justify engineering investment." },
    caseStudy: "A product manager at a grocery app was pressured to add 20 requested features at once. Instead, she ranked them by customer impact and engineering effort, and shipped only the top 3 — 'search autocomplete,' 'save favourite lists,' and 'faster checkout' — which alone improved conversion by double digits, proving that focus beats breadth.",
    founderQuestion: "If you could only ship ONE feature this month, which one would create the most customer value with the least effort — and how would you prove it?",
    quiz: [
      { id: "d22q1", question: "What is the core job of a product manager?", options: ["Writing all the code", "Deciding what to build and why, balancing customer and business needs", "Only designing the UI", "Managing company finances"], correctIndex: 1, explanation: "PMs decide priorities and direction, not necessarily execution details." },
      { id: "d22q2", question: "Why is saying 'no' an important product management skill?", options: ["To be difficult", "Focus on the highest-impact work requires rejecting many good-but-lower-priority ideas", "To save money only", "It's not actually important"], correctIndex: 1, explanation: "Limited resources require ruthless prioritisation of the highest-impact work." },
      { id: "d22q3", question: "What did the grocery app's product manager prioritise?", options: ["All 20 requested features at once", "The top 3 highest-impact, lowest-effort features", "Only the cheapest feature", "Nothing — she delayed all features"], correctIndex: 1, explanation: "She ranked by impact vs. effort and shipped only the highest-value items." },
    ],
    takeaways: ["A product is anything that solves a customer problem in exchange for value.", "Product management is about deciding what to build and why — not just execution.", "Saying no to good ideas is essential to focus on great ones.", "Rank features by customer impact vs. effort before committing resources."],
    rememberThis: "Product management is the art of deciding what NOT to build.",
  },
  {
    id: "day-23", day: 23, phaseId: "product", slug: "pmf-revisited",
    title: "Product-Market Fit (Product Lens)",
    objective: "Revisit product-market fit specifically from a product design perspective — what to build to reach it.",
    concept: "While Day 13 covered PMF conceptually, today focuses on the PRODUCT decisions that help you reach it: narrowing scope, removing friction, and doubling down on the single feature customers love most (the 'core loop').",
    simpleExplanation: "Products that reach PMF usually do ONE thing extremely well before expanding, rather than doing many things adequately.",
    analogy: "Think of sharpening a pencil — more force applied to a narrow point cuts through faster than the same force spread across a blunt edge.",
    businessExample: "WhatsApp famously stayed intensely focused on fast, reliable messaging for years before adding payments, status, or business tools — the narrow focus was core to its global PMF.",
    indiaExample: "CRED focused narrowly on credit card bill payments with rewards before expanding into other financial products — nailing one core loop first.",
    commonMistake: "Adding many features simultaneously while chasing PMF, which dilutes the core experience and makes it hard to tell which feature is actually driving (or blocking) adoption.",
    exercise: { prompt: "For a habit-tracking app, identify the single 'core loop' feature that most directly delivers value, and one feature you'd deliberately NOT build yet.", answer: "Example: Core loop = a one-tap daily check-in with a visible streak counter. Deliberately skip (for now) = social sharing/leaderboards, since the core habit-forming loop must work first." },
    caseStudy: "A note-taking app added AI summarisation, calendar sync, and team chat all within its first 3 months, trying to compete broadly. Usage stayed flat. After stripping back to just 'fast, reliable note capture,' retention improved sharply — proving that narrow focus, not feature breadth, drove PMF.",
    founderQuestion: "If you had to delete 80% of your planned features and keep only the single most-loved one, which would survive — and why?",
    quiz: [
      { id: "d23q1", question: "What product strategy commonly helps reach PMF?", options: ["Building many features simultaneously", "Narrowing focus to one strong core loop before expanding", "Copying every competitor feature", "Ignoring customer feedback"], correctIndex: 1, explanation: "Depth in one core feature usually beats breadth across many mediocre ones." },
      { id: "d23q2", question: "What did WhatsApp prioritise for years before expanding?", options: ["Social media features", "Fast, reliable messaging", "Online shopping", "Video games"], correctIndex: 1, explanation: "Intense focus on core messaging reliability drove its global adoption." },
      { id: "d23q3", question: "What happened when the note-taking app stripped back to core features?", options: ["Usage dropped further", "Retention improved sharply", "Nothing changed", "They lost all customers"], correctIndex: 1, explanation: "Focusing on the core value proposition improved user retention." },
    ],
    takeaways: ["Reaching PMF usually requires narrowing focus to one strong core loop.", "Feature breadth too early can dilute and confuse the core value proposition.", "Identify your single most-loved feature and double down on it.", "Resist the urge to build many features simultaneously while still searching for PMF."],
    rememberThis: "Depth in one loved feature beats breadth across many average ones.",
  },
  {
    id: "day-24", day: 24, phaseId: "product", slug: "mvp-design",
    title: "MVP Design",
    objective: "Learn practical frameworks for scoping an MVP's exact feature set.",
    concept: "MVP design uses prioritisation frameworks like MoSCoW (Must have, Should have, Could have, Won't have) to decide exactly which features belong in version one, avoiding both an under-built and over-built MVP.",
    simpleExplanation: "Every feature idea gets sorted into one of four buckets: Must (the product fails without it), Should (important but not critical for launch), Could (nice but easily postponed), Won't (explicitly excluded for now).",
    analogy: "MoSCoW is like packing a suitcase for a short trip — you separate 'must pack' (passport) from 'nice to have' (extra shoes) so you don't overpack and miss your flight.",
    businessExample: "For a ride-hailing MVP: Must = request a ride, see driver location, pay. Should = rate the driver. Could = schedule rides in advance. Won't (for now) = multi-stop trips.",
    formula: { name: "MoSCoW Prioritisation", expression: "Must-have: launch blocker\nShould-have: important, not blocking\nCould-have: nice, low priority\nWon't-have: explicitly excluded now", workedExample: "A food delivery MVP: Must = browse menu, order, pay. Should = order tracking. Could = scheduled orders. Won't = loyalty rewards program (for v1)." },
    commonMistake: "Labelling too many features as 'Must have' out of fear of launching an incomplete product — true MVPs usually have a surprisingly short Must-have list.",
    exercise: { prompt: "For an online tutoring booking platform, sort these into MoSCoW: video call integration, tutor ratings, payment, scheduling, referral program, multi-language support.", answer: "Must: scheduling, payment, video call integration (core functionality). Should: tutor ratings (builds trust but not launch-blocking). Could: multi-language support. Won't (for v1): referral program." },
    caseStudy: "A fintech startup building a bill-splitting app initially listed 15 'must-have' features including group chat, expense analytics, and currency conversion. After applying MoSCoW rigorously, only 'add expense' and 'split evenly' survived as true must-haves — the MVP shipped in 3 weeks instead of the originally planned 4 months.",
    founderQuestion: "Using MoSCoW on your own idea, what are your TRUE must-haves — and are you being honest, or just afraid to launch small?",
    quiz: [
      { id: "d24q1", question: "What does the 'S' in MoSCoW stand for?", options: ["Simple", "Should-have", "Scalable", "Secure"], correctIndex: 1, explanation: "Should-have features are important but not launch-blocking." },
      { id: "d24q2", question: "Why do founders often over-populate the 'Must-have' category?", options: ["They want to save money", "Fear of launching an incomplete product", "Investors demand it", "It's a legal requirement"], correctIndex: 1, explanation: "Fear of 'not being ready' often leads to bloated must-have lists, delaying launch." },
      { id: "d24q3", question: "What happened after the fintech startup applied MoSCoW rigorously?", options: ["They added more features", "Their true MVP shrank to 2 core features and shipped in 3 weeks", "The project was cancelled", "Nothing changed"], correctIndex: 1, explanation: "Rigorous prioritisation dramatically reduced scope and sped up launch." },
    ],
    takeaways: ["MoSCoW (Must/Should/Could/Won't) is a practical MVP scoping framework.", "True MVP must-have lists are usually shorter than founders initially think.", "Explicitly deciding 'Won't have (for now)' prevents scope creep.", "Rigorous prioritisation can dramatically speed up time-to-launch."],
    rememberThis: "If everything is a 'must-have,' nothing actually is.",
  },
  {
    id: "day-25", day: 25, phaseId: "product", slug: "product-roadmap",
    title: "Product Roadmap",
    objective: "Learn how to plan and communicate the sequence of future product work.",
    concept: "A product roadmap is a visual plan showing what a product team intends to build, in what sequence, and why — organised by themes or outcomes (e.g. 'improve onboarding') rather than rigid exact dates.",
    simpleExplanation: "A good roadmap communicates PRIORITY and DIRECTION, not a fixed promise of exact ship dates — because priorities shift as you learn more from customers.",
    analogy: "A roadmap is like a travel itinerary with flexible connections — you know the destinations and rough order, but you leave room to adjust based on weather (market feedback) along the way.",
    businessExample: "A SaaS company's roadmap might show: Q1 theme = 'improve onboarding,' Q2 theme = 'add team collaboration features,' Q3 theme = 'enterprise security compliance' — themes, not exact feature lists with fixed dates.",
    indiaExample: "A fintech startup's public roadmap might show upcoming themes like 'faster KYC verification' and 'multi-language support' without committing to exact release dates, since regulatory approval timing is uncertain.",
    commonMistake: "Publishing a roadmap with fixed exact dates for features far in the future — this creates false promises when priorities inevitably shift based on new learning.",
    exercise: { prompt: "Create a 3-quarter roadmap (by THEME, not exact feature) for a food delivery app aiming to expand from one city to a national presence.", answer: "Example: Q1 theme = 'operational excellence in current city' (faster delivery, fewer order errors). Q2 theme = 'expansion readiness' (standardise onboarding for new cities). Q3 theme = 'national rollout' (launch in 5 new cities)." },
    caseStudy: "A startup published a public roadmap promising a major feature 'by March.' Customer feedback in January revealed a more urgent, different need. Because the roadmap was theme-based rather than date-locked, the team could honestly communicate a shift in priority without breaking a hard promise — preserving customer trust.",
    founderQuestion: "What are the 3 biggest THEMES (not individual features) your product should focus on over the next 2 quarters, and why those three?",
    quiz: [
      { id: "d25q1", question: "What should a good product roadmap primarily communicate?", options: ["Exact daily tasks for engineers", "Priority and direction, organised by theme", "Company financial statements", "Employee salaries"], correctIndex: 1, explanation: "Roadmaps communicate strategic direction and sequencing, not granular task lists." },
      { id: "d25q2", question: "Why is a theme-based roadmap often better than a date-locked feature list?", options: ["Themes are always shorter", "It allows flexibility as priorities shift based on new learning", "Dates are illegal to publish", "Themes are easier to design visually"], correctIndex: 1, explanation: "Flexibility prevents false promises when customer feedback shifts priorities." },
      { id: "d25q3", question: "How did a theme-based roadmap help the startup in the case study?", options: ["It let them hide problems from customers", "It let them honestly shift priorities without breaking a hard date promise", "It eliminated the need for planning", "It guaranteed on-time delivery"], correctIndex: 1, explanation: "Flexibility preserved trust when new, more urgent needs emerged." },
    ],
    takeaways: ["A roadmap communicates priority and direction, usually by theme.", "Avoid locking in exact dates for features far in the future.", "Roadmaps should flex as new customer learning emerges.", "Themes (e.g. 'improve onboarding') are more durable than specific feature promises."],
    rememberThis: "A roadmap is a compass showing direction, not a train schedule promising exact arrival times.",
  },
  {
    id: "day-26", day: 26, phaseId: "product", slug: "features-vs-benefits",
    title: "Features vs Benefits",
    objective: "Learn to translate technical features into customer-facing benefits.",
    concept: "A feature is what the product DOES (technical capability). A benefit is what the customer GETS (the real-world value or outcome). Customers buy benefits, not features — even though companies often market features by habit.",
    simpleExplanation: "Feature: 'Power BI dashboard.' Benefit: 'A manager can understand sales performance in 30 seconds, without waiting for a report.' The benefit answers 'so what?' for the customer.",
    analogy: "A feature is a drill; the benefit is the hole in the wall the customer actually wanted — nobody buys a drill because they love drills, they buy it to hang a picture.",
    businessExample: "Apple rarely leads marketing with 'A15 chip specifications' (feature) — it leads with 'take stunning photos in low light without a flash' (benefit).",
    indiaExample: "A fintech app might have the feature 'instant UPI autopay setup,' but markets the benefit: 'never miss a bill payment or late fee again.'",
    commonMistake: "Listing technical specifications in marketing copy without translating them into the real outcome a customer cares about — this is common in engineering-led startups.",
    exercise: { prompt: "Translate these features into customer benefits: (1) '256-bit encryption' for a password manager. (2) 'Same-day delivery' for an online pharmacy.", answer: "(1) Benefit: 'Your passwords stay safe even if your phone is lost or hacked.' (2) Benefit: 'Never run out of essential medicine — get it the same day you need it.'" },
    caseStudy: "A B2B software company's sales deck was full of technical jargon ('multi-threaded processing,' '99.99% uptime SLA') and conversions were low. After rewriting the deck around benefits ('your team never loses work to downtime,' 'reports that used to take an hour now take seconds'), demo-to-close conversion improved significantly.",
    founderQuestion: "Pick your product's most technical feature. If you only had 10 words to explain why a customer should care, what would you say?",
    quiz: [
      { id: "d26q1", question: "What is the key difference between a feature and a benefit?", options: ["They are the same thing", "A feature is what the product does; a benefit is the real value the customer gets", "Features are always more expensive", "Benefits are only for B2C products"], correctIndex: 1, explanation: "A benefit translates technical capability into real customer outcome." },
      { id: "d26q2", question: "Which is an example of a BENEFIT (not a feature)?", options: ["'256-bit encryption'", "'Your passwords stay safe even if your phone is lost'", "'Multi-threaded processing'", "'99.99% uptime SLA'"], correctIndex: 1, explanation: "This translates a technical capability into a real, relatable customer outcome." },
      { id: "d26q3", question: "What happened after the B2B company rewrote its deck around benefits?", options: ["Nothing changed", "Demo-to-close conversion improved significantly", "Prices increased", "They lost customers"], correctIndex: 1, explanation: "Benefit-focused messaging resonated better and improved conversion." },
    ],
    takeaways: ["Customers buy benefits (outcomes), not features (technical capabilities).", "Always ask 'so what?' after describing a feature to find the real benefit.", "Marketing and sales copy should lead with benefits, not specifications.", "Engineering-led teams often need deliberate practice translating features into benefits."],
    rememberThis: "Nobody buys a drill for the drill — they buy it for the hole.",
  },
  {
    id: "day-27", day: 27, phaseId: "product", slug: "ux-customer-experience",
    title: "UX and Customer Experience",
    objective: "Understand how user experience (UX) design directly impacts business outcomes.",
    concept: "UX (User Experience) is how a customer FEELS while using your product — ease, clarity, delight, or frustration. Poor UX causes drop-off even when the underlying product solves a real problem; great UX reduces friction and increases retention and referrals.",
    simpleExplanation: "A product can solve a real problem perfectly in theory, but if it's confusing or slow to use, customers abandon it before ever experiencing that value.",
    analogy: "UX is like the path to a great restaurant — if the entrance is hard to find, dirty, or confusing, many hungry customers will turn away before even tasting the food.",
    businessExample: "Google's homepage stayed famously minimal (just a search box) because every extra element added friction and slowed down the core action users wanted — searching.",
    indiaExample: "PhonePe and Google Pay invested heavily in reducing the number of taps needed to complete a UPI payment, directly because each extra step measurably increased drop-off rates.",
    commonMistake: "Adding visual polish (nice colours, animations) while ignoring core usability issues like confusing navigation or too many required steps — polish without usability doesn't fix drop-off.",
    exercise: { prompt: "List the steps a new user takes to sign up and complete their first action in an app you use often. Identify one step that feels unnecessary or confusing.", answer: "Example (food delivery app): Download → sign up with phone number → OTP verification → enter address → browse → add to cart → enter payment → confirm. A common friction point: requiring address entry BEFORE allowing any menu browsing, which could be reordered to reduce early drop-off." },
    caseStudy: "An e-commerce startup noticed many users abandoned checkout at the payment step. Removing just one unnecessary field (asking for a secondary phone number) and enabling 'guest checkout' (no forced account creation) reduced cart abandonment by a meaningful margin — a small UX fix with a large business impact.",
    founderQuestion: "What is the single most confusing or frustrating step in your product's current user journey, and what would it take to remove it entirely?",
    quiz: [
      { id: "d27q1", question: "Why can a technically great product still fail due to poor UX?", options: ["Technical quality doesn't matter at all", "Confusing or frustrating experiences cause customers to abandon before experiencing the value", "UX only matters for games", "Poor UX always means a product is cheap"], correctIndex: 1, explanation: "Friction in the experience prevents customers from ever reaching the product's real value." },
      { id: "d27q2", question: "Why did Google keep its homepage extremely minimal?", options: ["To save server costs", "To reduce friction and keep focus on the core search action", "Because no one liked colour", "It was a legal requirement"], correctIndex: 1, explanation: "Minimal design reduces distraction and friction around the primary user action." },
      { id: "d27q3", question: "What UX fix reduced cart abandonment for the e-commerce startup?", options: ["Adding more fields to checkout", "Removing an unnecessary field and enabling guest checkout", "Raising prices", "Adding more images"], correctIndex: 1, explanation: "Reducing friction at checkout directly improved conversion." },
    ],
    takeaways: ["UX is how a customer feels while using your product, not just how it looks.", "Friction in onboarding or checkout causes drop-off even for genuinely valuable products.", "Small UX fixes (removing one unnecessary step) can have outsized business impact.", "Polish without usability doesn't solve core friction problems."],
    rememberThis: "A great product with confusing UX is a locked door with treasure behind it.",
  },
  {
    id: "day-28", day: 28, phaseId: "product", slug: "product-case-study-day",
    title: "Product Case Study Day",
    objective: "Apply product fundamentals, MVP design, roadmapping, features vs benefits, and UX thinking to a real analysis.",
    concept: "This review day asks you to analyse a real product end-to-end: what's its core loop, what would its MVP have looked like, what features vs benefits does it emphasise in marketing, and where does its UX create friction or delight.",
    simpleExplanation: "This is the kind of structured product-thinking exercise product managers do constantly when studying competitors or onboarding onto a new product team.",
    analogy: "Think of this like a food critic deconstructing a dish — not just tasting it, but understanding every ingredient and technique that makes it work (or not).",
    businessExample: "Analysing Swiggy: Core loop = order food → get it delivered reliably and fast. Likely early MVP = a basic listings site with manual order coordination in one city. Marketing benefit (not just feature) = 'your favourite food, delivered fast and hot,' not 'we have a logistics algorithm.' UX detail = real-time order tracking reduces customer anxiety during the wait.",
    indiaExample: "Analysing CRED: Core loop = pay credit card bill → earn rewards. Benefit-led marketing = 'get rewarded for paying bills on time,' not 'we have bill-payment APIs.' UX detail = an exclusive, premium design builds a sense of status for members.",
    commonMistake: "Describing a product only by its features list instead of analysing its core loop, benefit framing, and UX friction points — a shallow analysis misses the real lessons.",
    exercise: { prompt: "Pick any app you use daily. Identify: (1) its core loop, (2) one feature it markets as a benefit, (3) one UX friction point you've personally experienced.", answer: "There's no single correct answer — the exercise is complete when all three elements are clearly and specifically identified, based on real personal experience with the app." },
    caseStudy: "A product management student analysed Zerodha's Kite trading app and noted its core loop (check portfolio → place trade → track performance) was kept deliberately simple compared to competitors with cluttered dashboards — concluding that Zerodha's growth was partly driven by UX simplicity in an industry known for overwhelming interfaces.",
    founderQuestion: "If a product analyst studied YOUR product today, what would they identify as your core loop, your best benefit-led message, and your biggest UX friction point?",
    quiz: [
      { id: "d28q1", question: "What does 'core loop' refer to in product analysis?", options: ["The company's org chart", "The repeated core action a user takes to get value from the product", "The pricing model", "The legal structure"], correctIndex: 1, explanation: "The core loop is the central repeated behaviour that delivers the product's value." },
      { id: "d28q2", question: "What did the product management student conclude about Zerodha's Kite app?", options: ["It had the most features", "Its UX simplicity in a cluttered industry contributed to its growth", "It was the cheapest option", "It had no core loop"], correctIndex: 1, explanation: "Deliberate simplicity differentiated it in an industry known for complexity." },
      { id: "d28q3", question: "Why is analysing only a feature list insufficient for real product analysis?", options: ["Feature lists are always wrong", "It misses the core loop, benefit framing, and UX friction that actually drive outcomes", "Features don't matter at all", "It takes too long to list features"], correctIndex: 1, explanation: "A full analysis requires understanding loop, messaging, and experience — not just a feature inventory." },
    ],
    takeaways: ["Real product analysis covers core loop, MVP history, benefit framing, and UX friction.", "Benefit-led marketing often beats feature-led marketing even for the same product.", "UX simplicity can be a genuine competitive advantage in cluttered industries.", "Apply this same structured analysis to your own product regularly."],
    rememberThis: "Analyse a product the way a critic analyses a dish: ingredients, technique, and the experience of eating it.",
  },
];
