import type { Lesson } from "../types";

export const phase02Lessons: Lesson[] = [
  {
    id: "day-8", day: 8, phaseId: "startup", slug: "what-is-a-startup",
    title: "What Is a Startup?",
    objective: "Define a startup precisely and understand the journey from idea to scalable company.",
    concept: "A startup is a young company designed to grow fast by solving a problem in a new, scalable way, usually under heavy uncertainty about whether customers will actually want it.",
    simpleExplanation: "A startup isn't just 'a new company' — it's a company built to test a risky idea quickly and grow it massively if the idea works.",
    analogy: "A startup is like a scientist running an experiment: you have a hypothesis (the idea), you test it on real customers, and you adjust fast based on results.",
    businessExample: "Dropbox started as a simple video demo to test if people wanted easy file-syncing before building the full product — a classic lean startup move.",
    indiaExample: "OYO began by testing whether standardising budget hotel rooms would make travellers book more confidently — a hypothesis it tested with a handful of hotels before scaling nationally.",
    startupExample: "Airbnb's founders tested their idea with just air mattresses in their own apartment before building a global marketplace.",
    commonMistake: "Spending months building a 'perfect' product before testing if anyone wants it — the opposite of how successful startups operate.",
    exercise: { prompt: "Think of a problem you face weekly. Write one sentence describing the riskiest assumption you'd need to test before building a full solution.", answer: "Example: Problem = finding reliable home tutors. Riskiest assumption = 'parents will trust an app-recommended tutor without meeting them first' — this must be tested with a small pilot before building anything bigger." },
    caseStudy: "A founder wanted to build an app for furniture rental. Instead of building the app immediately, she posted rental listings on Instagram and WhatsApp to see if anyone would actually rent furniture this way. Only after getting real paying customers did she invest in building the app.",
    founderQuestion: "What is the single riskiest assumption in your business idea, and how could you test it this week for under ₹5,000?",
    quiz: [
      { id: "d8q1", question: "What makes a startup different from just 'a new company'?", options: ["It must use an app", "It's built to test and scale a risky, repeatable idea fast", "It must lose money", "It must have investors"], correctIndex: 1, explanation: "The defining trait is testing a scalable idea under uncertainty, not age or funding." },
      { id: "d8q2", question: "Why did Dropbox make a demo video before building the full product?", options: ["To save money on marketing", "To test demand before investing in full development", "Because video was trendy", "To attract investors only"], correctIndex: 1, explanation: "It validated real customer interest cheaply before committing engineering resources." },
      { id: "d8q3", question: "What should a founder identify before building a full product?", options: ["The company's final valuation", "The riskiest assumption to test first", "The office address", "The hiring plan"], correctIndex: 1, explanation: "Testing the riskiest assumption first avoids wasted effort on unwanted products." },
    ],
    takeaways: ["A startup tests a scalable idea fast under real uncertainty.", "Validate the riskiest assumption before full development.", "Cheap experiments (landing pages, manual pilots) often beat building a full product first.", "Startups are temporary by design — they either find a scalable model or pivot/stop."],
    rememberThis: "A startup is an experiment in search of a scalable business model.",
  },
  {
    id: "day-9", day: 9, phaseId: "startup", slug: "problem-vs-solution",
    title: "Problem vs Solution",
    objective: "Learn to separate the customer's real problem from your proposed solution.",
    concept: "A problem is the pain or need a customer experiences. A solution is your specific answer to that problem. Founders often fall in love with their solution and forget to validate whether the problem is real, painful, and common enough.",
    simpleExplanation: "Problem = 'I'm always late because traffic apps don't account for local shortcuts.' Solution = 'An app using local shortcut data.' Many founders start with the solution and reverse-engineer a problem to justify it — this is backwards.",
    analogy: "The problem is the itch; the solution is the scratch. If you invent a fancy scratching tool for an itch nobody has, nobody buys it.",
    businessExample: "Slack's team originally built a gaming company, but noticed their internal messaging tool solved a real painful problem (chaotic team communication) better than their original game idea — so they pivoted the solution to match the real problem.",
    indiaExample: "Urban Company (formerly UrbanClap) was built around the real, painful problem of finding trustworthy home service professionals (plumbers, electricians) — the solution (a vetted marketplace) came after understanding that pain deeply.",
    commonMistake: "Describing a solution ('an app that does X') without being able to clearly state the problem it solves and for whom.",
    exercise: { prompt: "State a business idea you have. Write the PROBLEM in one sentence, separate from the SOLUTION, in another sentence.", answer: "Example — Problem: 'Small shop owners struggle to track daily cash sales accurately.' Solution: 'A simple voice-based ledger app for shopkeepers.'" },
    caseStudy: "A founder built a beautifully designed app for 'organizing recipes' but struggled to get users. After talking to 50 home cooks, she realised the real problem was not recipe organization — it was 'deciding what to cook with ingredients already at home.' She rebuilt the solution around THAT problem and engagement tripled.",
    founderQuestion: "Can you describe your target customer's problem without mentioning your product at all? If not, you may not understand the problem yet.",
    quiz: [
      { id: "d9q1", question: "What is the danger of starting with a solution instead of a problem?", options: ["Solutions are always expensive", "You may build something nobody actually needs", "Problems don't matter to customers", "Solutions take longer to build"], correctIndex: 1, explanation: "Without a validated problem, even a well-built solution can fail to find customers." },
      { id: "d9q2", question: "Which is a correctly stated PROBLEM (not a solution)?", options: ["\"We need an app with AI chat\"", "\"Shopkeepers struggle to track daily cash sales accurately\"", "\"We should build a dashboard\"", "\"Our app needs more features\""], correctIndex: 1, explanation: "This describes a customer pain point, with no mention of a specific solution." },
      { id: "d9q3", question: "How did Slack's team arrive at their real product?", options: ["Market research reports", "Noticing their internal tool solved a real painful problem better than their original idea", "A government grant", "Pure luck with no signal"], correctIndex: 1, explanation: "They recognized a validated internal need and pivoted the solution toward it." },
    ],
    takeaways: ["Always separate the problem from the solution in your thinking.", "Validate the problem's pain and frequency before building a solution.", "If you can't state the problem without mentioning your product, you may not understand it yet.", "Talking to real customers reveals the true problem better than assumptions."],
    rememberThis: "Fall in love with the problem, not your first solution.",
  },
  {
    id: "day-10", day: 10, phaseId: "startup", slug: "finding-business-ideas",
    title: "Finding Business Ideas",
    objective: "Learn systematic ways to discover real, valuable business ideas instead of waiting for inspiration.",
    concept: "Good ideas usually come from noticing friction: things that are slow, expensive, confusing, or annoying in everyday life or work. Founders can find ideas by observing their own frustrations, talking to people in an industry, studying emerging trends, or looking at successful models in one market that haven't reached another.",
    simpleExplanation: "Instead of asking 'what cool app can I build?', ask 'what annoys people so much that they'd pay to make it go away?'",
    analogy: "Finding a business idea is like metal detecting — you don't invent treasure, you search patiently in the right places (daily frustrations, inefficient industries, underserved groups) until you find it.",
    businessExample: "Nykaa's founder noticed Indian consumers had no trustworthy place to discover and buy a wide range of beauty products online with expert guidance — that gap became the business.",
    indiaExample: "Meesho noticed many homemakers wanted to earn income through reselling but lacked access to suppliers or e-commerce tools — a clear underserved need became a large marketplace.",
    startupExample: "Many YC-backed startups come from founders solving a problem they personally experienced in a previous job, then realising thousands of others had the same unsolved problem.",
    mnemonic: { label: "F.I.T.", breakdown: ["F = Frustration you personally feel", "I = Industry inefficiency you observe", "T = Trend about to become mainstream"] },
    commonMistake: "Chasing an idea just because it's trendy (e.g. 'AI for everything') without any personal insight or evidence that a real customer group is suffering from the problem.",
    exercise: { prompt: "List 3 things that annoyed you in the last week. For each, write who else likely has the same problem.", answer: "Example: (1) Slow grocery delivery at odd hours → busy professionals. (2) Hard to track shared household expenses with roommates → students/young professionals. (3) Confusing warranty claims for electronics → all appliance owners." },
    caseStudy: "A founder repeatedly struggled to find a reliable, affordable packers-and-movers service when relocating for work. After discovering friends had the same frustration, he built a vetted-mover marketplace focused on urban professionals who relocate frequently for jobs.",
    founderQuestion: "What's one industry you understand well (through work, family, or hobbies) that still runs inefficiently? What would you fix first?",
    quiz: [
      { id: "d10q1", question: "Which is the best starting point for finding a business idea?", options: ["Copying a trending app exactly", "Noticing real, recurring frustration in daily life or work", "Waiting for sudden inspiration", "Choosing the most 'exciting' technology"], correctIndex: 1, explanation: "Recurring, real frustration is the most reliable signal of an underlying business opportunity." },
      { id: "d10q2", question: "In the F.I.T. mnemonic, what does the 'I' stand for?", options: ["Investment", "Industry inefficiency", "Innovation only", "Internet"], correctIndex: 1, explanation: "I stands for Industry inefficiency — a gap you observe in how an industry currently operates." },
      { id: "d10q3", question: "What is risky about chasing trendy ideas without personal insight?", options: ["Trends are always fake", "You may lack real understanding of the customer's actual pain", "Trendy ideas are illegal", "Trends never make money"], correctIndex: 1, explanation: "Without real insight into customer pain, trend-chasing often produces solutions nobody needs." },
    ],
    takeaways: ["Good ideas come from observing real, recurring frustration — not random inspiration.", "Use F.I.T.: Frustration, Industry inefficiency, Trend.", "Personal experience with a problem is a strong (though not sufficient) signal.", "Validate that others share the same frustration before committing."],
    rememberThis: "Don't invent a solution and search for a problem — find the problem first.",
  },
  {
    id: "day-11", day: 11, phaseId: "startup", slug: "idea-validation",
    title: "Idea Validation",
    objective: "Learn practical, low-cost ways to test whether a business idea has real demand before building it.",
    concept: "Validation means gathering real evidence — not opinions — that customers have the problem and would pay for your solution. Evidence can include pre-orders, sign-ups, pilot sales, or committed conversations, not just 'that sounds like a good idea' feedback.",
    simpleExplanation: "Asking friends 'would you use this?' is weak validation (people are polite). Getting 20 strangers to pre-pay a small deposit is strong validation.",
    analogy: "Validation is like testing if a bridge can hold weight before you drive a truck over it — small, controlled tests before full commitment.",
    businessExample: "Before building their own courier network, many D2C brands first validate demand using pre-order campaigns on Instagram, only manufacturing once enough orders are confirmed.",
    indiaExample: "Many Indian D2C food and skincare brands run 'coming soon' waitlist pages with a small deposit before launch, to gauge real demand before committing to inventory.",
    formula: { name: "Validation Signal Strength", expression: "Weak: opinions/compliments\nMedium: sign-ups/waitlist\nStrong: pre-payments/pilot purchases", workedExample: "100 waitlist sign-ups = medium signal. 20 of those convert to a ₹200 pre-order deposit = strong signal — it shows real willingness to pay." },
    commonMistake: "Treating compliments from friends and family as proof of demand. Real validation requires money, time, or commitment from strangers.",
    exercise: { prompt: "You have an idea for a meal-prep subscription. Design one cheap validation test you could run this week for under ₹2,000.", answer: "Example: Create a simple landing page describing the meal plan and price, run a small local ad, and ask visitors to pay a ₹100 refundable deposit to join a 'founding member' waitlist. Count real deposits, not just visits." },
    caseStudy: "A founder wanted to launch a subscription box for regional Indian snacks. Instead of manufacturing 1,000 boxes upfront, she sold 50 'pre-launch' boxes on Instagram first. Only 12 sold — revealing weak demand before she had spent money on inventory, saving her from a costly mistake.",
    founderQuestion: "What is the cheapest, fastest experiment you could run this week to get real evidence (not opinions) about your idea?",
    quiz: [
      { id: "d11q1", question: "Which of these is the STRONGEST validation signal?", options: ["A friend saying 'great idea!'", "100 people pre-paying a deposit", "A survey with positive responses", "Your own gut feeling"], correctIndex: 1, explanation: "Money committed by strangers is the strongest evidence of real demand." },
      { id: "d11q2", question: "Why is feedback from friends and family considered weak validation?", options: ["They always lie", "They tend to be polite and supportive regardless of real interest", "They never understand business", "It's illegal to ask them"], correctIndex: 1, explanation: "Social politeness bias makes friends/family unreliable indicators of true market demand." },
      { id: "d11q3", question: "What did the snack subscription founder learn from her pre-launch test?", options: ["Demand was very strong", "Demand was weaker than expected, saving her from overinvesting", "The product was too cheap", "Nothing useful"], correctIndex: 1, explanation: "Only 12 of 50 boxes sold, revealing weak real demand before costly inventory investment." },
    ],
    takeaways: ["Validation requires real evidence (money, time, commitment) — not opinions.", "Pre-orders and deposits are stronger signals than sign-ups or compliments.", "Run cheap, fast experiments before investing significant money.", "Weak validation results are valuable — they prevent costly mistakes."],
    rememberThis: "Validation = evidence of a stranger's money or time, not a friend's opinion.",
  },
  {
    id: "day-12", day: 12, phaseId: "startup", slug: "mvp",
    title: "MVP (Minimum Viable Product)",
    objective: "Understand how to build the smallest possible version of a product that still delivers real value and teaches you something.",
    concept: "An MVP (Minimum Viable Product) is the simplest version of your product that lets real customers experience its core value, so you can learn from their behaviour before investing in a full build.",
    simpleExplanation: "MVP is not a 'broken' or 'ugly' product — it's a focused product that does ONE thing well enough to be genuinely useful, skipping every nice-to-have feature.",
    analogy: "If your end goal is a car, your MVP is a skateboard, not a half-built car missing wheels. A skateboard is incomplete but fully functional and useful right now.",
    businessExample: "Zappos' founder famously validated online shoe-buying demand by manually photographing shoes from local stores and listing them online, buying from the store himself only when someone ordered — no warehouse, no inventory, just a test of the core idea.",
    indiaExample: "Many Indian quick-commerce startups began their MVP with a small set of products delivered from a single local dark store in one neighbourhood, before expanding to a citywide network.",
    startupExample: "Dropbox's MVP was literally a short demo video explaining the product, used purely to measure sign-up interest before any code was written.",
    commonMistake: "Building an MVP with too many features ('minimum viable' becomes 'maximum version 1') which delays learning and wastes resources.",
    exercise: { prompt: "You want to build a platform matching freelance tutors with students. Design an MVP that could be tested in one week with no app.", answer: "Example MVP: A WhatsApp group or simple Google Form where students submit requests, and you manually match them with 3-5 known tutors, collecting payment via UPI — testing demand and matching logic before building any software." },
    caseStudy: "A founder wanted to build a grocery delivery app for a small town. Instead of building the app first, he started by taking orders over WhatsApp and delivering them himself on a bike. This MVP let him learn delivery times, popular items, and pricing sensitivity — all before writing a single line of code.",
    founderQuestion: "What is the smallest version of your idea that a real customer could use TODAY, with no coding and under ₹5,000?",
    quiz: [
      { id: "d12q1", question: "What is the core purpose of an MVP?", options: ["To look impressive to investors", "To test the core value with real customers while learning fast", "To include every planned feature", "To avoid talking to customers"], correctIndex: 1, explanation: "An MVP exists to validate the core value proposition and generate learning, not to be feature-complete." },
      { id: "d12q2", question: "Which best describes a good MVP?", options: ["A half-finished car missing wheels", "A fully functional skateboard that solves part of the bigger problem", "A detailed business plan document", "A fully-featured but unlaunched product"], correctIndex: 1, explanation: "A good MVP is simple but genuinely functional and useful right now." },
      { id: "d12q3", question: "What was Dropbox's original MVP?", options: ["A fully coded app", "A short demo video to test sign-up interest", "A physical hard drive", "A Kickstarter campaign only"], correctIndex: 1, explanation: "The demo video tested demand cheaply before any engineering investment." },
    ],
    takeaways: ["An MVP tests core value with the least possible effort — it's not a broken product.", "Skip nice-to-have features; focus only on the core value proposition.", "Manual, non-software MVPs (WhatsApp, forms, spreadsheets) are valid and often smarter.", "The goal of an MVP is learning, not impressing."],
    rememberThis: "MVP = the smallest thing that still delivers real value and teaches you something.",
  },
  {
    id: "day-13", day: 13, phaseId: "startup", slug: "product-market-fit",
    title: "Product-Market Fit",
    objective: "Understand what product-market fit (PMF) really means and how to recognise early signs of it.",
    concept: "Product-market fit happens when a product satisfies a strong market demand so well that customers actively want it, use it repeatedly, and tell others about it — growth starts to feel like it's pulling itself rather than being pushed.",
    simpleExplanation: "Before PMF, you're pushing hard for every single customer and they barely engage. After PMF, customers come back on their own and growth feels easier, even though you're not working any harder.",
    analogy: "Finding PMF is like finally finding the right key for a lock — before, you're jamming the wrong keys trying to force it open; once you find the right one, the door swings open with almost no effort.",
    businessExample: "Instagram originally launched as a complex app (Burbn) with many features and saw weak engagement. After stripping it down to just photo-sharing with filters, usage exploded — that was the moment of product-market fit.",
    indiaExample: "Swiggy found strong product-market fit once it focused specifically on fast food delivery logistics rather than trying to be a generic listings directory like early competitors.",
    formula: { name: "Simple PMF signal", expression: "Ask: 'How would you feel if you could no longer use this product?'\n40%+ saying 'Very disappointed' = a strong PMF signal (Sean Ellis test)", workedExample: "If you survey 100 active users and 45 say they'd be 'very disappointed' without your product, that's a strong signal you may have PMF." },
    commonMistake: "Trying to scale marketing spend aggressively BEFORE reaching product-market fit — this just burns money pushing an unwanted product faster.",
    exercise: { prompt: "If you ran the 'very disappointed' survey (Sean Ellis test) on your current product idea's target users, what % do you honestly think would say 'very disappointed' if it disappeared? What would you need to change to get that number above 40%?", answer: "There's no single correct answer — the exercise is about honestly estimating current product strength and identifying the single biggest gap preventing a higher score." },
    caseStudy: "A food delivery startup struggled with low repeat orders for a year despite heavy marketing. After interviewing churned customers, they discovered delivery times (not price or selection) were the real blocker. Once they fixed logistics and cut delivery time in half, repeat order rates tripled — a clear signal they had finally reached product-market fit.",
    founderQuestion: "If your paid marketing stopped completely tomorrow, would customers still come back on their own? What does your honest answer tell you about your current product-market fit?",
    quiz: [
      { id: "d13q1", question: "What is the clearest sign of strong product-market fit?", options: ["High marketing spend", "Customers returning and referring others with little extra push", "A large team", "A fancy office"], correctIndex: 1, explanation: "Organic retention and referral, not spend, signal real product-market fit." },
      { id: "d13q2", question: "What mistake did Instagram's team fix to reach PMF?", options: ["They added more features", "They stripped the app down to focus on photo-sharing", "They increased prices", "They changed their name only"], correctIndex: 1, explanation: "Simplifying to the core valued feature (photo-sharing) is what drove adoption." },
      { id: "d13q3", question: "Why is scaling marketing spend before PMF risky?", options: ["Marketing is always a bad investment", "It accelerates spending to push a product that isn't truly wanted yet", "Ads don't work for startups", "It's illegal"], correctIndex: 1, explanation: "Without PMF, more marketing just accelerates the burn rate without durable growth." },
    ],
    takeaways: ["PMF is when customers pull the product toward them instead of you pushing it.", "The Sean Ellis 'very disappointed' test is a simple way to gauge PMF.", "Fix the product (not just marketing) if repeat usage/retention is weak.", "Don't scale spend aggressively before PMF is reasonably confirmed."],
    rememberThis: "Before PMF you push growth; after PMF, growth starts pulling you.",
  },
  {
    id: "day-14", day: 14, phaseId: "startup", slug: "startup-case-study-day",
    title: "Startup Case Study Day",
    objective: "Apply the full startup journey — problem, customer, solution, MVP, feedback, PMF — to real company stories.",
    concept: "Today connects Days 8-13 into one framework: Problem → Customer → Solution → MVP → Feedback → Product-Market Fit. This is the lifecycle nearly every successful startup moves through, even if the order sometimes loops back.",
    simpleExplanation: "Think of this as the 'startup funnel of truth': you start with a believed problem, test a cheap solution (MVP) with real customers, gather honest feedback, iterate, and — if the problem and solution truly match — eventually reach product-market fit.",
    analogy: "This journey is like adjusting a camera lens: problem and customer set the rough frame, the MVP and feedback loop zoom and refocus repeatedly, until the picture (PMF) finally comes into sharp focus.",
    businessExample: "Airbnb: Problem (expensive, impersonal hotel stays) → Customer (budget travellers, conference attendees) → Solution (renting air mattresses) → MVP (a simple website for their own apartment) → Feedback (people wanted more than mattresses — whole homes) → PMF (a trusted global home-sharing marketplace).",
    indiaExample: "OYO: Problem (inconsistent quality in budget hotels) → Customer (value-conscious domestic travellers) → Solution (standardised branded budget rooms) → MVP (a handful of partner hotels in one city) → Feedback (travellers wanted predictable pricing and amenities) → PMF (rapid nationwide expansion).",
    startupExample: "Uber's journey followed the same path: Problem (unreliable taxis) → Customer (urban professionals) → Solution (on-demand private car booking) → MVP (a simple app in San Francisco with a handful of drivers) → Feedback (riders wanted faster pickup and transparent pricing) → PMF (global ride-hailing dominance).",
    commonMistake: "Assuming the journey is strictly linear. In reality, founders often loop back — feedback from an MVP frequently reveals the ORIGINAL problem definition was slightly wrong, requiring a return to Day 9's problem-vs-solution thinking.",
    exercise: { prompt: "Pick Dropbox, Zomato, or OYO. Map their journey using the six stages: Problem, Customer, Solution, MVP, Feedback, PMF.", answer: "Example — Zomato: Problem (no easy way to discover restaurant menus/reviews) → Customer (urban diners) → Solution (an online restaurant directory) → MVP (a simple listings website for one city) → Feedback (users wanted delivery, not just discovery) → PMF (expanding into full food delivery)." },
    caseStudy: "Reviewing OYO's early years: it started as 'Oravel Stays,' a listing site for budget accommodations (closer to Airbnb). Customer feedback and ground realities (inconsistent quality, trust issues) pushed the founder to pivot the SOLUTION from 'listing' to 'standardising and branding' budget hotels directly — eventually finding strong product-market fit as OYO.",
    founderQuestion: "Looking at your own idea, which of the six stages (Problem, Customer, Solution, MVP, Feedback, PMF) are you most confident about, and which is the weakest link right now?",
    quiz: [
      { id: "d14q1", question: "What are the six stages of the startup journey covered this week?", options: ["Idea, Money, Team, Office, Launch, Profit", "Problem, Customer, Solution, MVP, Feedback, PMF", "Logo, Website, App, Ads, Sales, Scale", "Plan, Pitch, Fund, Build, Market, Exit"], correctIndex: 1, explanation: "This is the core lean-startup lifecycle taught across Days 8-13." },
      { id: "d14q2", question: "Why is the startup journey often non-linear?", options: ["Founders are disorganised", "Feedback from an MVP can reveal the original problem was misdefined, requiring a loop back", "Investors demand it", "It's a myth — it's always linear"], correctIndex: 1, explanation: "Real-world feedback regularly forces founders to revisit and refine earlier stages." },
      { id: "d14q3", question: "What pivot did OYO make based on customer feedback?", options: ["From food delivery to hotels", "From listing budget hotels to standardising and branding them directly", "From B2C to B2B only", "From India to global first"], correctIndex: 1, explanation: "OYO shifted from a passive listing model to actively standardising hotel quality and branding." },
    ],
    takeaways: ["The lean startup journey: Problem → Customer → Solution → MVP → Feedback → PMF.", "Real startups loop back through these stages repeatedly — it's rarely linear.", "Studying real case studies reveals patterns that apply broadly across industries.", "Identify your own weakest link in this chain and focus there next."],
    rememberThis: "Problem → Customer → Solution → MVP → Feedback → PMF — and loop back whenever feedback demands it.",
  },
];
