import type { Lesson } from "../types";

export const phase07Lessons: Lesson[] = [
  {
    id: "day-43", day: 43, phaseId: "operations", slug: "operations-fundamentals",
    title: "Operations Fundamentals",
    objective: "Understand operations as the engine that reliably turns inputs into outputs at scale.",
    concept: "Operations is the function responsible for executing the business's core promise consistently — turning Inputs (raw materials, labour, time) through a Process into reliable Outputs (products/services delivered to customers), day after day.",
    simpleExplanation: "Great marketing and sales can get a customer to try you once — great operations is what makes sure every single order, every single time, is delivered reliably and well, which is what keeps customers coming back.",
    analogy: "Operations is the invisible plumbing behind a building — nobody notices it when it works perfectly, but everyone notices instantly when a pipe bursts.",
    businessExample: "McDonald's built a global empire not on secret recipes, but on operational excellence — standardised processes mean a burger in Delhi tastes consistent with one in Chicago.",
    indiaExample: "DMart's profitability is driven heavily by operational discipline — efficient store layouts, inventory management, and supply chain negotiation, not flashy marketing.",
    formula: { name: "Input → Process → Output", expression: "INPUT (materials, labour, time) → PROCESS (the repeatable method) → OUTPUT (the delivered product/service)", workedExample: "A laundry service: Input = dirty clothes + detergent + machines + staff time. Process = sorting, washing, drying, folding, packaging. Output = clean, folded clothes delivered on time." },
    commonMistake: "Treating operations as a boring 'back office' function, when in reality operational consistency is often the actual competitive advantage customers experience most directly and repeatedly.",
    exercise: { prompt: "For a home-cooked-meal delivery service, list the Inputs, the Process steps, and the Output.", answer: "Inputs: raw ingredients, cooks, packaging materials, delivery staff/vehicles. Process: menu planning → sourcing ingredients → cooking → packaging → dispatch → delivery. Output: a hot, correctly packed meal delivered on time to the customer's door." },
    caseStudy: "A food delivery startup had great marketing and strong initial sign-ups, but orders were frequently late or incorrect due to poor kitchen coordination. Despite excellent marketing, customer churn stayed high until they fixed their operational process (better kitchen-to-rider handoff coordination) — proving operations, not marketing, was their real bottleneck to growth.",
    founderQuestion: "If 1,000 new customers tried your product tomorrow because of a viral marketing success, would your current operations reliably deliver a good experience to all of them?",
    quiz: [
      { id: "d43q1", question: "What is the core job of operations?", options: ["Designing marketing campaigns", "Reliably turning inputs into outputs through a consistent process", "Raising investment", "Hiring salespeople"], correctIndex: 1, explanation: "Operations executes the business's core delivery promise consistently." },
      { id: "d43q2", question: "Why is operational consistency often an underrated competitive advantage?", options: ["It's cheap to copy", "Customers experience it directly and repeatedly, more than marketing or branding", "It doesn't affect customer experience", "It's irrelevant to growth"], correctIndex: 1, explanation: "Reliable delivery, experienced repeatedly, builds trust more than one-time marketing messages." },
      { id: "d43q3", question: "What was the real bottleneck for the food delivery startup in the case study?", options: ["Weak marketing", "Poor kitchen-to-rider coordination causing late/incorrect orders", "Too much funding", "Too many customers"], correctIndex: 1, explanation: "Operational breakdowns, not marketing, were driving customer churn." },
    ],
    takeaways: ["Operations reliably converts Inputs into Outputs through a repeatable Process.", "Operational consistency is often a hidden but powerful competitive advantage.", "Marketing can attract customers once, but operations determines if they return.", "Map your own Input → Process → Output chain to find weak links."],
    rememberThis: "Marketing gets the first order; operations earns the second one.",
  },
  {
    id: "day-44", day: 44, phaseId: "operations", slug: "process-design",
    title: "Process Design",
    objective: "Learn to design clear, repeatable processes that reduce errors and improve speed.",
    concept: "Process design means intentionally mapping every step of a workflow, removing unnecessary steps, and standardising the remaining ones so any trained team member can execute the work consistently — regardless of who's doing it.",
    simpleExplanation: "A well-designed process shouldn't depend on one 'hero' employee who remembers everything — it should work the same way even if that person is on leave.",
    analogy: "Process design is like writing a recipe clearly enough that a stranger could cook the same dish correctly without ever meeting the original chef.",
    businessExample: "Toyota's famous production system redesigned manufacturing processes to eliminate waste and errors at each step, becoming a global benchmark for process efficiency.",
    indiaExample: "Haldiram's standardised snack production processes across multiple factories to ensure consistent taste and quality regardless of location — a deliberate process design choice enabling nationwide scale.",
    commonMistake: "Relying on tribal knowledge ('ask Raj, he knows how we do this') instead of documenting the process — this creates a dangerous single point of failure and makes onboarding new staff slow and inconsistent.",
    exercise: { prompt: "Pick a repeated task in your life or business (e.g. responding to customer complaints). Write it as a numbered, step-by-step process that someone else could follow without asking you questions.", answer: "Example — Customer complaint process: 1) Acknowledge the complaint within 2 hours. 2) Ask for order ID and specific issue. 3) Check order history. 4) Offer resolution (refund/replacement) based on a defined policy. 5) Follow up within 24 hours to confirm satisfaction." },
    caseStudy: "A growing bakery relied entirely on its founder's memory for daily ingredient ordering, causing frequent shortages whenever she was away. After documenting a clear ordering process (based on sales data triggers, not memory), any staff member could place accurate orders — eliminating shortages and reducing the founder's daily workload.",
    founderQuestion: "Which critical process in your business currently exists only in one person's head, and what would happen if that person left tomorrow?",
    quiz: [
      { id: "d44q1", question: "What is a key goal of good process design?", options: ["Make processes depend on one expert employee", "Make the process repeatable and consistent regardless of who executes it", "Add as many steps as possible", "Avoid documentation"], correctIndex: 1, explanation: "Consistency independent of any single individual is the core goal." },
      { id: "d44q2", question: "What risk does relying on 'tribal knowledge' create?", options: ["No risk at all", "A single point of failure if that person is unavailable, plus slow onboarding", "It makes processes faster", "It reduces training needs"], correctIndex: 1, explanation: "Undocumented knowledge concentrated in one person creates fragility." },
      { id: "d44q3", question: "What fixed the bakery's ingredient shortage problem?", options: ["Hiring more staff", "Documenting a clear, data-driven ordering process anyone could follow", "Buying more ovens", "Closing earlier"], correctIndex: 1, explanation: "A documented, repeatable process removed dependence on one person's memory." },
    ],
    takeaways: ["Good process design makes work repeatable regardless of who executes it.", "Document processes instead of relying on one person's memory ('tribal knowledge').", "Map steps clearly enough that a new employee could follow them unaided.", "Identify and fix single points of failure in your current processes."],
    rememberThis: "A good process works the same way even when your best employee is on vacation.",
  },
  {
    id: "day-45", day: 45, phaseId: "operations", slug: "sop",
    title: "SOP (Standard Operating Procedure)",
    objective: "Learn how to write effective SOPs that ensure consistent quality across a team.",
    concept: "An SOP (Standard Operating Procedure) is a written, step-by-step document describing exactly how to perform a specific task, ensuring consistency, quality, and faster onboarding regardless of who performs it.",
    simpleExplanation: "An SOP turns 'how we do things' from an unwritten habit into a clear, repeatable, teachable document.",
    analogy: "An SOP is like an aircraft pre-flight checklist — pilots with decades of experience still follow it exactly, because consistency prevents costly mistakes, even for experts.",
    businessExample: "Fast-food chains use detailed SOPs for food preparation (exact cooking times, portion sizes) ensuring a consistent product regardless of which employee or location prepares it.",
    indiaExample: "Hospital chains like Apollo use SOPs for patient intake and hygiene protocols across branches, ensuring consistent care quality and safety standards nationwide.",
    commonMistake: "Writing SOPs that are too vague ('handle customer complaints professionally') instead of specific and actionable ('respond within 2 hours; offer a refund if the issue isn't resolved within 24 hours').",
    exercise: { prompt: "Write a short SOP (3-5 numbered steps) for 'onboarding a new customer' for a subscription box service.", answer: "Example SOP: 1) Send a welcome email within 1 hour of sign-up, including delivery date. 2) Confirm shipping address via automated text. 3) Dispatch first box within 48 hours. 4) Send a tracking link once shipped. 5) Follow up with a satisfaction check 3 days after delivery." },
    caseStudy: "A cleaning services startup had inconsistent customer satisfaction because each cleaner had their own approach. After introducing a simple, specific SOP (exact cleaning checklist and order of tasks per room), customer satisfaction scores became far more consistent across different cleaners, regardless of individual experience level.",
    founderQuestion: "Which task in your business most urgently needs a written SOP because quality currently varies depending on who performs it?",
    quiz: [
      { id: "d45q1", question: "What is the main purpose of an SOP?", options: ["To restrict employee creativity", "To ensure consistent quality and faster onboarding regardless of who performs the task", "To replace all employees with documents", "To reduce the need for training"], correctIndex: 1, explanation: "SOPs standardise execution for consistency, not to limit judgment unnecessarily." },
      { id: "d45q2", question: "Why do even expert pilots follow detailed pre-flight checklists?", options: ["It's a legal formality with no real value", "Consistency prevents costly mistakes, even for highly experienced people", "Checklists are only for beginners", "Checklists replace piloting skill"], correctIndex: 1, explanation: "Checklists reduce human error regardless of experience level." },
      { id: "d45q3", question: "What fixed the cleaning startup's inconsistent satisfaction scores?", options: ["Hiring only experienced cleaners", "A specific, written SOP standardising the cleaning checklist and task order", "Charging higher prices", "Reducing the number of cleaners"], correctIndex: 1, explanation: "A specific SOP standardised quality regardless of individual cleaner experience." },
    ],
    takeaways: ["An SOP is a specific, written, step-by-step procedure for a task.", "SOPs should be specific and actionable, not vague.", "Even experts benefit from following SOPs — they reduce costly errors.", "Identify tasks with inconsistent quality as priority candidates for an SOP."],
    rememberThis: "An SOP turns 'how we usually do it' into 'how we always do it, correctly.'",
  },
  {
    id: "day-46", day: 46, phaseId: "operations", slug: "supply-chain",
    title: "Supply Chain",
    objective: "Understand the end-to-end flow of materials and products from source to customer.",
    concept: "A supply chain is the full network of suppliers, manufacturers, warehouses, and delivery partners involved in getting a product from raw material to the final customer. Managing it well means balancing cost, speed, and reliability.",
    simpleExplanation: "Every product you buy travelled through a chain of hands before reaching you — understanding and managing that chain determines cost, availability, and customer satisfaction.",
    analogy: "A supply chain is like a relay race — if any single runner (link) stumbles, the whole race (delivery) is delayed, no matter how fast the others run.",
    businessExample: "Zara is famous for an unusually fast, tightly managed supply chain that gets new fashion designs from sketch to store shelf in weeks instead of the industry-standard months.",
    indiaExample: "Reliance Retail invested heavily in building its own backend supply chain (warehousing, logistics) to reduce dependency on third parties and control costs and delivery speed across its retail network.",
    commonMistake: "Relying entirely on a single supplier for a critical input — any disruption (price change, shortage, quality issue) with that one supplier can halt the entire business.",
    exercise: { prompt: "For a small furniture business, map out the supply chain from raw wood to a finished chair in the customer's home, in 4-5 steps.", answer: "Example: Raw timber supplier → wood processing/treatment → furniture workshop (manufacturing) → warehouse (finished goods storage) → delivery partner → customer's home." },
    caseStudy: "A D2C skincare brand relied on a single overseas supplier for a key ingredient. When that supplier faced a shipping delay, the brand ran out of stock for 6 weeks, losing significant sales and customer trust. After the incident, they deliberately diversified to two suppliers in different regions to reduce this single-point-of-failure risk.",
    founderQuestion: "Which single supplier, if they disappeared tomorrow, would most severely disrupt your business — and what's your backup plan?",
    quiz: [
      { id: "d46q1", question: "What does a supply chain include?", options: ["Only the final retail store", "The full network of suppliers, manufacturers, warehouses, and delivery getting a product to the customer", "Only marketing partners", "Only the company's own factory"], correctIndex: 1, explanation: "A supply chain spans the entire journey from raw material to final customer delivery." },
      { id: "d46q2", question: "What risk does relying on a single supplier for a critical input create?", options: ["No risk — single suppliers are always safer", "Any disruption with that one supplier can halt the entire business", "It automatically lowers costs with no downside", "It's required by law to use multiple suppliers"], correctIndex: 1, explanation: "A single point of failure can severely disrupt operations if something goes wrong." },
      { id: "d46q3", question: "How did the skincare brand respond after their supply disruption?", options: ["They shut down the product line", "They diversified to two suppliers in different regions", "They raised prices only", "They ignored the issue"], correctIndex: 1, explanation: "Supplier diversification reduced future single-point-of-failure risk." },
    ],
    takeaways: ["A supply chain is the full network from raw material to final customer delivery.", "Managing supply chains balances cost, speed, and reliability.", "Over-reliance on a single supplier creates serious disruption risk.", "Fast, well-managed supply chains (like Zara's) can become a major competitive advantage."],
    rememberThis: "A supply chain is a relay race — one stumble anywhere in the chain delays the whole delivery.",
  },
  {
    id: "day-47", day: 47, phaseId: "operations", slug: "inventory",
    title: "Inventory",
    objective: "Learn the basics of managing stock levels to balance availability against cost.",
    concept: "Inventory is the stock of raw materials, work-in-progress, or finished goods a business holds. Too little inventory causes stockouts and lost sales; too much ties up cash and risks waste or obsolescence. Good inventory management finds the right balance.",
    simpleExplanation: "Holding inventory costs money (storage, risk of spoilage/obsolescence) even while sitting unsold — so businesses aim to hold just enough to meet demand without excess waste.",
    analogy: "Inventory is like keeping food in your fridge — too little means running out mid-week (stockout); too much means spoiled, wasted food (excess inventory cost).",
    businessExample: "Amazon's sophisticated inventory forecasting predicts regional demand precisely enough to position stock in the right warehouses before customers even order, minimising both stockouts and excess storage.",
    indiaExample: "Kirana stores traditionally manage inventory through experience and intuition about local demand patterns, while larger chains like DMart use data-driven inventory systems to minimise both stockouts and overstock across hundreds of SKUs.",
    formula: { name: "Simple Inventory Turnover", expression: "Inventory Turnover = Cost of Goods Sold ÷ Average Inventory Value", workedExample: "COGS = ₹24,00,000 per year. Average inventory value = ₹4,00,000. Inventory Turnover = 24,00,000 ÷ 4,00,000 = 6 times per year (inventory is fully sold and replaced 6 times a year)." },
    commonMistake: "Over-ordering stock 'just to be safe' without considering the cash tied up and the risk of unsold goods becoming obsolete or spoiled — especially risky for perishable or fashion-trend-driven products.",
    exercise: { prompt: "A bakery has an annual Cost of Goods Sold of ₹12,00,000 and an average inventory value of ₹1,00,000. Calculate inventory turnover and explain what a very LOW turnover number would suggest.", answer: "Inventory Turnover = 12,00,000 ÷ 1,00,000 = 12 times per year. A very low turnover (e.g. 2 times per year) would suggest the bakery is overstocking relative to sales, tying up cash and risking spoilage of perishable goods." },
    caseStudy: "A clothing retailer overordered a trendy style expecting high demand, but the trend faded faster than expected, leaving excess unsold inventory that had to be heavily discounted, eroding margin. A competitor using smaller, more frequent restocking batches based on real-time sales data avoided this trap, maintaining healthier margins.",
    founderQuestion: "If you had to cut your current inventory levels by 30% without risking stockouts, what would you need to improve about your demand forecasting?",
    quiz: [
      { id: "d47q1", question: "What problem does holding too MUCH inventory create?", options: ["No problem at all", "Cash gets tied up, with risk of waste or obsolescence", "It always increases sales", "It eliminates the need for suppliers"], correctIndex: 1, explanation: "Excess inventory locks up cash and risks spoilage or going out of fashion/relevance." },
      { id: "d47q2", question: "What does a HIGH inventory turnover number generally indicate?", options: ["Poor sales", "Inventory is being sold and replaced efficiently relative to its value", "The business is losing money", "Too much storage space is being used"], correctIndex: 1, explanation: "Higher turnover generally reflects efficient inventory management relative to sales." },
      { id: "d47q3", question: "What mistake did the clothing retailer make?", options: ["Ordering too little stock", "Overordering a trend-driven style that faded faster than expected", "Not advertising enough", "Pricing too low"], correctIndex: 1, explanation: "Overstocking a fast-fading trend led to costly discounting and margin erosion." },
    ],
    takeaways: ["Inventory management balances availability against the cost of holding stock.", "Inventory Turnover = COGS ÷ Average Inventory Value.", "Overstocking ties up cash and risks waste/obsolescence; understocking causes lost sales.", "Real-time, frequent restocking based on actual demand reduces risk versus large upfront orders."],
    rememberThis: "Inventory sitting unsold is cash sitting unused, quietly at risk of spoiling.",
  },
  {
    id: "day-48", day: 48, phaseId: "operations", slug: "quality-management",
    title: "Quality Management",
    objective: "Learn how businesses systematically maintain and improve the quality of their product or service.",
    concept: "Quality management involves setting clear quality standards, measuring performance against them (often via KPIs), identifying bottlenecks or defects, and continuously improving processes to reduce errors and increase efficiency.",
    simpleExplanation: "Quality isn't a one-time achievement — it's an ongoing system of measurement and improvement, because small defects compound into major customer trust problems if left unchecked.",
    analogy: "Quality management is like a doctor's regular health check-ups — catching small issues early (a slightly elevated metric) prevents them from becoming major problems later.",
    businessExample: "Toyota's quality management system empowers any assembly line worker to stop the entire production line the moment they spot a defect, preventing faulty products from ever reaching customers — a famous example of built-in quality control.",
    indiaExample: "Titan (Tata Group) built its watch and jewellery brand reputation significantly on strict in-house quality checks at every manufacturing stage, which became a key trust differentiator in the Indian market.",
    mnemonic: { label: "KPI / SLA / Bottleneck", breakdown: ["KPI = Key Performance Indicator (a specific number you track to measure quality/performance)", "SLA = Service Level Agreement (a committed standard, e.g. 'respond within 24 hours')", "Bottleneck = the step in a process that limits overall speed or quality"] },
    commonMistake: "Measuring quality only through customer complaints (a lagging indicator) instead of proactive internal checks that catch issues before they ever reach the customer.",
    exercise: { prompt: "For a food delivery service, define one KPI, one SLA, and identify a likely bottleneck in their delivery process.", answer: "Example: KPI = average delivery time (minutes). SLA = 'deliver within 30 minutes or the order is free.' Likely bottleneck = kitchen preparation time during peak lunch hours, which slows down the entire chain regardless of how fast delivery riders are." },
    caseStudy: "A manufacturing company only discovered product defects through customer returns, which was costly and damaged their reputation. After introducing in-line quality checks (inspecting products at each manufacturing stage, not just at the end), defect rates dropped significantly before products ever reached customers.",
    founderQuestion: "What is one quality issue your customers currently discover AFTER the fact, that you could instead catch internally before it ever reaches them?",
    quiz: [
      { id: "d48q1", question: "What is a KPI?", options: ["A legal contract", "A Key Performance Indicator — a specific number tracked to measure performance/quality", "A type of inventory", "A marketing channel"], correctIndex: 1, explanation: "KPIs are specific measurable metrics used to track performance over time." },
      { id: "d48q2", question: "Why is relying only on customer complaints a weak quality control method?", options: ["Complaints are always exaggerated", "It's a lagging indicator — problems are caught only after they've already harmed the customer", "Complaints are illegal to track", "Customers never complain about quality"], correctIndex: 1, explanation: "Proactive internal checks catch issues before customers are affected, unlike complaint-based detection." },
      { id: "d48q3", question: "What change reduced the manufacturing company's defect rate?", options: ["Hiring more salespeople", "Introducing in-line quality checks at each manufacturing stage", "Lowering production speed only", "Ignoring customer returns"], correctIndex: 1, explanation: "Catching defects during production, not just at the end, proactively reduced issues reaching customers." },
    ],
    takeaways: ["Quality management uses KPIs and SLAs to measure and maintain standards continuously.", "A bottleneck is the step limiting overall process speed or quality.", "Proactive internal checks beat relying only on customer complaints.", "Toyota's 'stop the line' philosophy shows how empowering early defect detection prevents bigger problems."],
    rememberThis: "Catch quality problems with internal checks before your customers catch them for you.",
  },
  {
    id: "day-49", day: 49, phaseId: "operations", slug: "operations-case-study-day",
    title: "Operations Case Study Day",
    objective: "Apply process design, SOPs, supply chain, inventory, and quality management to a realistic operational scenario.",
    concept: "This review day connects Days 43-48 into one applied analysis: given a growing business, identify its Input-Process-Output chain, where an SOP is missing, supply chain risk, inventory concerns, and a quality bottleneck.",
    simpleExplanation: "This mirrors the kind of operational audit a COO or operations consultant would perform when a growing business starts experiencing cracks under increased order volume.",
    analogy: "Think of this like a mechanic inspecting a car after it starts making a strange noise at higher speeds — the issue only shows up under load, requiring systematic diagnosis across every major system.",
    businessExample: "A growing bakery chain scaling from 1 to 5 locations might face: missing SOPs (inconsistent recipes across new locations), supply chain risk (single flour supplier can't scale fast enough), inventory issues (perishable ingredients spoiling at slower-selling locations), and a quality bottleneck (only the founder can properly judge dough consistency, limiting how fast new locations can open).",
    indiaExample: "Many Indian restaurant chains scaling rapidly face exactly this pattern — recipes that worked perfectly at one location become inconsistent at ten, revealing the need for documented SOPs, diversified sourcing, and standardised quality training rather than reliance on a single skilled chef.",
    commonMistake: "Assuming operational problems will 'fix themselves with growth' — in reality, growth usually magnifies small operational weaknesses into major, visible failures.",
    exercise: { prompt: "Pick a real or imagined growing business (5-10 locations or rapidly scaling online). Identify: one missing SOP, one supply chain risk, one inventory issue, and one likely quality bottleneck.", answer: "There's no single correct answer — the exercise is complete when each of the four operational weaknesses is specifically and plausibly identified, based on realistic growth pressures." },
    caseStudy: "A regional grocery delivery startup expanded from 2 to 15 cities within a year. Growth exposed operational cracks: inconsistent packing quality (no SOP), delayed deliveries in new cities (unprepared supply chain), expired perishables in low-demand areas (poor inventory forecasting), and rising complaint rates (no proactive quality checks). Fixing these four areas systematically, rather than individually reacting to each complaint, stabilised their expansion.",
    founderQuestion: "If your business doubled in size overnight, which single operational weakness would break first — and what would you need to fix today to prevent that?",
    quiz: [
      { id: "d49q1", question: "What commonly happens to small operational weaknesses as a business grows?", options: ["They automatically resolve themselves", "Growth tends to magnify small weaknesses into major, visible failures", "Growth has no effect on operations", "Operations become less important"], correctIndex: 1, explanation: "Scale tends to expose and amplify operational cracks that were manageable at a smaller size." },
      { id: "d49q2", question: "What should be identified in a full operational audit of a scaling business?", options: ["Only the marketing budget", "Missing SOPs, supply chain risk, inventory issues, and quality bottlenecks", "Only the company logo", "Only employee salaries"], correctIndex: 1, explanation: "A complete operational audit covers process, supply, inventory, and quality systematically." },
      { id: "d49q3", question: "How did the grocery delivery startup stabilise its expansion?", options: ["By slowing down growth only", "By systematically fixing SOPs, supply chain, inventory, and quality issues together", "By raising more funding only", "By ignoring the complaints"], correctIndex: 1, explanation: "A systematic fix across all four operational areas, not isolated reactions, stabilised the expansion." },
    ],
    takeaways: ["Operational weaknesses often get magnified, not fixed automatically, by growth.", "A full operational audit covers process/SOPs, supply chain, inventory, and quality.", "Fix operational weaknesses systematically before scaling further, not reactively after failures.", "Anticipating which weakness would 'break first' under growth is a valuable founder exercise."],
    rememberThis: "Growth doesn't fix operational weaknesses — it finds them and breaks them in public.",
  },
];
