import type { Lesson } from "../types";

export const phase01Lessons: Lesson[] = [
  {
    id: "day-1", day: 1, phaseId: "business", slug: "what-is-a-business",
    title: "What Is a Business?",
    objective: "Understand what a business really is and the pieces every business is made of.",
    concept:
      "A business is an organised way of creating something valuable for other people (customers) and getting paid for it. Every business — big or small — has the same core pieces: a customer with a problem, a solution to that problem, a way to earn revenue, and a way to keep the money flowing (cash flow) inside a wider ecosystem of suppliers, competitors and partners.",
    simpleExplanation:
      "If you cannot name a customer, you do not have a business — you have a hobby. A business exists only because it creates VALUE for someone else, and that someone else is willing to pay for it.",
    analogy:
      "Think of a business like a water pump: customers pour problems in on one side, and value flows out the other side. Revenue is the water that flows back in to keep the pump running.",
    businessExample:
      "A bakery takes flour, sugar and labour (inputs), turns them into bread (value), sells it to hungry neighbours (customers), and collects money (revenue) that pays for more flour tomorrow.",
    indiaExample: "A local kirana store solves the problem of \"I need groceries nearby, right now\" — its entire business exists around that one customer need.",
    startupExample: "Zerodha started because founders noticed that stockbroking in India was expensive and confusing for retail investors — that unmet need became the business.",
    mnemonic: {
      label: "VALUE",
      breakdown: ["V = Value you create", "A = Audience you serve", "L = Leverage (what makes you efficient)", "U = Utility (the real usefulness to the customer)", "E = Earnings (how you get paid)"],
    },
    commonMistake: "Beginners describe their business by what they SELL (\"I sell cakes\") instead of the PROBLEM they solve (\"I help people celebrate without the stress of baking\"). Selling a problem-solution story is far more powerful than selling a product.",
    exercise: {
      prompt: "Pick 5 businesses you interact with weekly (e.g. Swiggy, your gym, a tea stall, Amazon, your barber). For each, write down: Customer, Problem, Solution, Revenue source.",
      answer: "Example — Swiggy: Customer = hungry people with no time to cook; Problem = cooking/ordering takes effort; Solution = app that delivers food fast; Revenue source = delivery fees + commission from restaurants.",
    },
    caseStudy: "A college student starts tutoring juniors for ₹500/session because she notices many students fail basic math. Within a year she has 20 regular students. She has unknowingly built a real business: a clear customer (struggling students), a clear problem (failing grades), a solution (personalised tutoring), and recurring revenue.",
    founderQuestion: "If your neighbourhood disappeared tomorrow, which 3 problems would people desperately need solved? Could any of them be a business?",
    quiz: [
      { id: "d1q1", question: "What is the one thing every real business MUST have?", options: ["A fancy logo", "A paying customer with a problem", "A big office", "Investors"], correctIndex: 1, explanation: "Without a customer willing to pay, there is no business — only an idea or a hobby." },
      { id: "d1q2", question: "In the VALUE mnemonic, what does 'E' stand for?", options: ["Effort", "Earnings", "Expansion", "Expense"], correctIndex: 1, explanation: "E stands for Earnings — how the business actually gets paid." },
      { id: "d1q3", question: "Which statement best describes a business (vs. a hobby)?", options: ["It makes the founder happy", "It creates value a customer pays for", "It has a website", "It is registered with the government"], correctIndex: 1, explanation: "Formal registration and websites are optional; a paying customer is not." },
    ],
    takeaways: [
      "A business = customer + problem + solution + revenue, operating inside an ecosystem.",
      "Value is not what you make — it's the benefit the customer experiences.",
      "Use the VALUE mnemonic to check any business idea quickly.",
      "Describe your business by the problem it solves, not just the product it sells.",
    ],
    rememberThis: "A business is simply a repeatable way to solve someone's problem and get paid for it.",
  },
  {
    id: "day-2", day: 2, phaseId: "business", slug: "how-businesses-make-money",
    title: "How Businesses Actually Make Money",
    objective: "Learn the difference between revenue, cost, profit, margin and cash flow — and why big revenue does not mean big profit.",
    concept:
      "Revenue is all the money a business receives from selling. Cost is everything it spends to make and deliver that sale. Profit is what's left after costs are subtracted from revenue. Margin shows profit as a percentage of revenue — it tells you how efficient the business is, regardless of size. Cash flow is the actual movement of cash in and out, which can differ from profit on paper (e.g. a customer who hasn't paid yet).",
    simpleExplanation:
      "Revenue is the money coming IN. Cost is money going OUT. Profit is what's left. A business can have huge revenue and still go bankrupt if costs eat it all up or cash doesn't arrive on time.",
    analogy: "Think of a bathtub: revenue is water flowing in from the tap, costs are water draining out the plughole, and profit is the water level that remains.",
    businessExample: "A restaurant with ₹10,00,000 in monthly sales and ₹7,00,000 in costs keeps ₹3,00,000 — a 30% margin. A competitor with the same ₹10,00,000 sales but ₹9,50,000 in costs keeps only ₹50,000 — a 5% margin. Same revenue, very different businesses.",
    indiaExample: "DMart is famous for running on thin margins (low prices) but very high sales volume — it makes profit through efficiency and scale, not high prices.",
    startupExample: "Many early-stage startups run at a loss on purpose (negative profit) while they grow their customer base fast, planning to become profitable later — this is a deliberate, risky strategy, not an accident.",
    formula: { name: "Profit & Margin", expression: "Profit = Revenue − Cost\nMargin % = (Profit ÷ Revenue) × 100", workedExample: "Revenue = ₹10,00,000, Cost = ₹7,00,000 → Profit = ₹3,00,000 → Margin = (3,00,000 ÷ 10,00,000) × 100 = 30%" },
    mnemonic: { label: "R-C-P-M", breakdown: ["R = Revenue (money in)", "C = Cost (money out)", "P = Profit (what remains)", "M = Margin (profit as a % — the efficiency score)"] },
    commonMistake: "Assuming high revenue automatically means a healthy business. A ₹1 crore revenue business with 2% margin is far weaker than a ₹20 lakh revenue business with 25% margin.",
    exercise: {
      prompt: "A clothing store has Revenue = ₹5,00,000 and Cost = ₹3,50,000. Calculate Profit and Margin %.",
      answer: "Profit = 5,00,000 − 3,50,000 = ₹1,50,000. Margin = (1,50,000 ÷ 5,00,000) × 100 = 30%.",
    },
    caseStudy: "Two food trucks each sell ₹50,000 worth of food a day. Truck A spends ₹45,000 on ingredients, rent and staff (10% margin). Truck B negotiates cheaper ingredients and simplifies its menu, spending only ₹35,000 (30% margin). Both have identical revenue, but Truck B is three times more profitable.",
    founderQuestion: "If you had to cut your costs by 20% without losing any customers, which three expenses would you look at first, and why?",
    quiz: [
      { id: "d2q1", question: "A business has Revenue ₹8,00,000 and Cost ₹6,00,000. What is the margin?", options: ["15%", "20%", "25%", "75%"], correctIndex: 2, explanation: "Profit = 2,00,000; Margin = 2,00,000/8,00,000 ×100 = 25%." },
      { id: "d2q2", question: "Why can a business with high revenue still fail?", options: ["Revenue is fake", "High costs or poor cash flow can erase profit", "Customers don't like high revenue", "It's impossible"], correctIndex: 1, explanation: "Profit (not revenue) and cash flow timing determine survival." },
      { id: "d2q3", question: "What does 'margin' measure?", options: ["Total sales volume", "Efficiency — profit as a % of revenue", "Number of employees", "Brand popularity"], correctIndex: 1, explanation: "Margin shows how much of every rupee of revenue turns into profit." },
    ],
    takeaways: [
      "Revenue ≠ Profit. Always ask 'what are the costs?' before judging a business.",
      "Profit = Revenue − Cost; Margin = Profit ÷ Revenue × 100.",
      "A smaller business with a higher margin can be healthier than a bigger one with a thin margin.",
      "Cash flow timing (when money actually arrives) matters as much as profit on paper.",
    ],
    rememberThis: "Revenue is vanity, profit is sanity, cash flow is reality.",
  },
  {
    id: "day-3", day: 3, phaseId: "business", slug: "types-of-businesses",
    title: "Types of Businesses",
    objective: "Recognise the major categories of businesses by who they sell to and how they operate.",
    concept:
      "Businesses are often classified by WHO they sell to (B2B, B2C, C2C, D2C, B2G) and by HOW they operate or deliver value (marketplace, subscription, SaaS, services, manufacturing, retail, franchise). Knowing the category helps you predict how a business makes money, who its customers are, and what its biggest challenges will be.",
    simpleExplanation:
      "B2B = selling to other businesses (e.g. Microsoft selling software to companies). B2C = selling directly to individual consumers (e.g. a clothing brand). C2C = consumers selling to each other (e.g. OLX). D2C = a brand selling directly to consumers, skipping retailers (e.g. a skincare brand selling only on its own website). B2G = selling to government bodies.",
    analogy: "Think of these labels like different lanes on a highway — all vehicles (businesses) are moving toward the same destination (revenue), but each lane has its own rules, speed and traffic.",
    businessExample: "Microsoft (B2B software), a neighbourhood clothing store (B2C retail), OLX (C2C marketplace), a D2C skincare startup selling only online, and a construction company supplying bridges to the government (B2G).",
    indiaExample: "Zoho sells B2B software to companies worldwide. Swiggy and Zomato run B2C marketplaces connecting restaurants and diners. Reliance and DMart run large-scale retail. Meesho enables small resellers (closer to C2C/B2B2C).",
    startupExample: "A SaaS startup like Freshworks sells subscription software to other businesses (B2B + SaaS), while a D2C startup like a mattress brand sells directly to consumers online, bypassing traditional retail.",
    mnemonic: { label: "Business Types", breakdown: ["B2B = Business to Business", "B2C = Business to Consumer", "C2C = Consumer to Consumer", "D2C = Direct to Consumer (skips the middleman)", "B2G = Business to Government"] },
    commonMistake: "Assuming one business can only be one type. Amazon is B2C (shopping), B2B (AWS cloud, wholesale), and a marketplace (third-party sellers) all at once.",
    exercise: {
      prompt: "Classify these: (1) A freelance graphic designer selling logos to local shops. (2) A furniture brand selling only through its own app. (3) A used-book exchange app between students.",
      answer: "(1) B2B services (designer sells to businesses). (2) D2C (direct to consumer, no middleman retailer). (3) C2C marketplace (consumer to consumer).",
    },
    caseStudy: "A spice brand used to sell only through supermarkets (losing a big cut of each sale to retailers). It launched its own website and app, selling directly to households — becoming a D2C business, keeping more margin and learning directly from customer data.",
    founderQuestion: "If you were starting a business tomorrow, would you rather sell to individual consumers or to other businesses? What would change about your pricing, trust-building, and sales cycle?",
    quiz: [
      { id: "d3q1", question: "A software company selling tools to other companies is an example of:", options: ["B2C", "B2B", "C2C", "B2G"], correctIndex: 1, explanation: "Selling to businesses, not individual end consumers, is B2B." },
      { id: "d3q2", question: "What makes a business 'D2C'?", options: ["It only sells abroad", "It sells directly to consumers, skipping retailers", "It is government-owned", "It has no employees"], correctIndex: 1, explanation: "D2C brands control the full relationship with the end customer by skipping middlemen." },
      { id: "d3q3", question: "OLX, where individuals sell used items to other individuals, is best described as:", options: ["B2B", "B2C", "C2C", "SaaS"], correctIndex: 2, explanation: "Consumer-to-consumer transactions define a C2C marketplace." },
    ],
    takeaways: [
      "Classify businesses by WHO they sell to (B2B/B2C/C2C/D2C/B2G) and HOW they deliver value (SaaS/marketplace/retail/etc).",
      "One company can operate multiple business types at once.",
      "The type shapes sales cycles, trust requirements, and pricing strategy.",
      "D2C brands trade retailer reach for higher margins and direct customer data.",
    ],
    rememberThis: "Ask 'who pays me, and how do they buy?' — the answer reveals the business type.",
  },
  {
    id: "day-4", day: 4, phaseId: "business", slug: "business-models",
    title: "Business Models",
    objective: "Learn the common ways businesses structure how they earn money.",
    concept:
      "A business model is the specific mechanism a company uses to convert its value into revenue. The same product can use very different models: subscription (recurring fee), freemium (free tier + paid upgrade), commission (a cut of each transaction), marketplace (connecting buyers and sellers), advertising (free for users, paid by advertisers), licensing (paid for rights to use something), franchise (paid for using a proven business system), usage-based (pay per use), transaction fee (fixed fee per transaction), and direct sales (one-time purchase).",
    simpleExplanation: "The business model answers: 'exactly how and when does money change hands?' Two companies solving the same problem can make money in completely different ways.",
    analogy: "Think of a business model like the type of toll booth on a highway — some charge a monthly pass (subscription), some charge per vehicle (transaction fee), some let you drive free but show you billboards (advertising).",
    businessExample: "Netflix uses subscription. Zoom uses freemium (free for short calls, paid for longer/larger meetings). Airbnb uses commission (a % of each booking). Google Search uses advertising. McDonald's uses franchise.",
    indiaExample: "Zomato Gold/Swiggy One use subscription for perks. Razorpay charges a transaction fee per payment processed. Zerodha charges flat brokerage fees (usage-based per trade).",
    startupExample: "Many SaaS startups start with freemium to get users hooked, then convert a percentage of free users to paid subscription plans once they need more features.",
    mnemonic: { label: "SAFE-MULT", breakdown: ["S = Subscription", "A = Advertising", "F = Freemium", "E = Enterprise (large custom contracts)", "M = Marketplace", "U = Usage-based", "L = Licensing", "T = Transaction fee"] },
    commonMistake: "Confusing the PRODUCT with the BUSINESS MODEL. 'We sell software' is not a business model — 'we charge ₹999/month per user' is.",
    exercise: {
      prompt: "A fitness app lets you track workouts for free, but charges ₹299/month for personalised AI coaching. Which business model is this, and why?",
      answer: "Freemium — the core product is free to build a large user base, and a paid upgrade (AI coaching) monetises the most engaged users.",
    },
    caseStudy: "A ride-hailing app initially charged drivers a flat monthly fee to list their cars. Few drivers joined because the fee felt risky upfront. Switching to a commission model (a % per ride) removed the upfront risk for drivers, and the driver base grew rapidly.",
    founderQuestion: "For your own business idea, would customers prefer to pay once, monthly, or per use? What does that choice do to your cash flow and customer relationship?",
    quiz: [
      { id: "d4q1", question: "Charging a small percentage of each transaction that happens on your platform is called:", options: ["Subscription", "Commission", "Licensing", "Freemium"], correctIndex: 1, explanation: "Commission models take a cut of each transaction value." },
      { id: "d4q2", question: "In the SAFE-MULT mnemonic, what does the second 'E' represent? (Hint: it's not in SAFE)", options: ["Expense", "Enterprise", "Engagement", "Export"], correctIndex: 1, explanation: "E in SAFE-MULT stands for Enterprise — large custom B2B deals." },
      { id: "d4q3", question: "A business model where users pay only based on how much they use a service is:", options: ["Freemium", "Franchise", "Usage-based", "Advertising"], correctIndex: 2, explanation: "Usage-based pricing scales the bill with consumption (e.g. cloud computing)." },
    ],
    takeaways: [
      "A business model is the mechanism for converting value into revenue — not the product itself.",
      "The same idea can be monetised through completely different models.",
      "Use SAFE-MULT to quickly brainstorm monetisation options for any idea.",
      "The right model depends on customer psychology — upfront risk vs. ongoing commitment.",
    ],
    rememberThis: "Business model = exactly how and when money changes hands.",
  },
  {
    id: "day-5", day: 5, phaseId: "business", slug: "business-vs-startup",
    title: "Business vs Startup",
    objective: "Understand what truly separates a 'startup' from a regular small business, scale-up, or enterprise.",
    concept:
      "A small business is typically built around a known, repeatable model (a restaurant, a salon) with modest, steady growth. A startup is a temporary organisation searching for a new, repeatable, and SCALABLE business model — often under high uncertainty and high risk, aiming for fast growth. A scale-up is a startup that has found its model and is now growing it aggressively. An enterprise is a large, mature organisation with established, stable operations.",
    simpleExplanation: "Not every new business is a 'startup.' A new bakery is a small business, even though it's brand new. A startup specifically is searching for a way to grow very fast by solving a problem for a very large number of people, usually with technology or an innovative model.",
    analogy: "A small business is like a hiking trail you already know — steady, predictable. A startup is like exploring uncharted territory looking for a shortcut that, once found, lets you travel at 10x speed.",
    businessExample: "A local tailor shop (small business, stable, limited scalability) vs. a startup building an app that lets anyone get custom tailoring nationwide through a network of local tailors (startup, scalable, searching for the right model).",
    indiaExample: "A single Udupi restaurant is a small business. A chain like Haldiram's that systemised and scaled across the country is an enterprise today, but was once a scale-up.",
    startupExample: "Airbnb started as a tiny idea (renting air mattresses in an apartment) but was built with the INTENT to scale to a global marketplace — that intent plus scalability is what made it a startup, not a small hospitality business.",
    mnemonic: { label: "S-I-R-R-G", breakdown: ["S = Scalability (can it grow 100x?)", "I = Innovation (new approach, product or model)", "R = Risk (high uncertainty)", "R = Repeatability (the model works again and again)", "G = Growth intent (explicitly aiming to grow fast)"] },
    commonMistake: "Calling every small new business a 'startup.' A startup is defined by its intent and ability to scale rapidly — not by how new or trendy it looks.",
    exercise: {
      prompt: "Classify: (1) A newly opened coffee shop with one location and no expansion plan. (2) A new app connecting coffee shops to office deliveries nationwide, aiming to expand to every city in 2 years.",
      answer: "(1) Small business — stable, local, not built to scale rapidly. (2) Startup — scalable model, high growth intent, solving a repeatable problem across many markets.",
    },
    caseStudy: "Two friends open a gym. One treats it as a lifestyle business, happy with one profitable location. The other wants to franchise it into 50 cities within 3 years using a repeatable, technology-enabled model — that one is now building a startup, even though the core product (a gym) is the same.",
    founderQuestion: "Is your idea meant to stay as one great local business, or do you want it to become something that works the same way in 100 different cities? Why?",
    quiz: [
      { id: "d5q1", question: "What primarily distinguishes a startup from a small business?", options: ["Startups are always online", "Startups search for a scalable, repeatable model under uncertainty", "Small businesses never make profit", "Startups have no customers"], correctIndex: 1, explanation: "Scalability, repeatability, and uncertainty define a startup, not size or age." },
      { id: "d5q2", question: "A 'scale-up' is best described as:", options: ["A failed startup", "A startup that found its model and is now growing it fast", "Any company with over 100 employees", "A government business"], correctIndex: 1, explanation: "Scale-ups have validated their model and are focused on aggressive growth." },
      { id: "d5q3", question: "Which is a core trait of a startup's business model?", options: ["It must involve software", "It must be repeatable and scalable", "It must be unprofitable at first", "It must raise funding"], correctIndex: 1, explanation: "Repeatability and scalability — not funding or software — are the defining traits." },
    ],
    takeaways: [
      "A startup is defined by its search for a scalable, repeatable model — not by age or size.",
      "Small businesses can be perfectly successful without ever becoming startups.",
      "Scale-ups have already found their model and are now executing growth.",
      "Ask: is this meant to work the same way in 100 cities? That answer reveals startup intent.",
    ],
    rememberThis: "Startup = searching for scale. Small business = running a known model well.",
  },
  {
    id: "day-6", day: 6, phaseId: "business", slug: "stakeholders",
    title: "Stakeholders",
    objective: "Identify everyone who is affected by, or has influence over, a business.",
    concept:
      "A stakeholder is any person or group with an interest in how a business performs. The main stakeholders are customers (buy the product), employees (do the work), founders (own the vision), investors (fund growth and expect returns), suppliers (provide inputs), government (regulates and taxes), partners (collaborate for mutual benefit), and society (affected by the business's broader impact).",
    simpleExplanation: "Every decision a business makes can help one stakeholder and hurt another — e.g. cutting prices pleases customers but can worry investors about margins. Good founders constantly balance these competing interests.",
    analogy: "A business is like a ship with many passengers aboard — customers, crew (employees), captain (founder), financiers, and even the ocean around it (society). The captain must steer in a way that keeps the ship moving while keeping everyone reasonably satisfied.",
    businessExample: "When a factory decides to automate, employees may worry about jobs, investors may be pleased about lower costs, customers may get cheaper products, and the government may be interested in the employment impact.",
    indiaExample: "When Reliance Jio launched with very low prices, customers benefited hugely, competitors (other telecoms) were hurt, suppliers of telecom equipment benefited, and the government saw rapid digital adoption — all stakeholders reacted differently to the same move.",
    startupExample: "A startup raising venture capital must balance founder vision, investor expectations for growth/returns, and employee equity incentives — often in tension with each other.",
    mnemonic: { label: "CEFISGPS", breakdown: ["C = Customers", "E = Employees", "F = Founders", "I = Investors", "S = Suppliers", "G = Government", "P = Partners", "S = Society"] },
    commonMistake: "Thinking only of customers and investors. Suppliers, employees, and society are often ignored until a crisis (e.g. a supply shortage or public backlash) forces attention onto them.",
    exercise: {
      prompt: "A clothing brand wants to cut costs by switching to a cheaper fabric supplier. Map how this decision could affect each stakeholder group: customers, employees, suppliers, investors, society.",
      answer: "Customers: may notice lower quality. Employees: may need retraining on new material. Suppliers: the old supplier loses business, the new one gains it. Investors: may be happy about improved margins short-term. Society: depends on whether the new supplier has ethical/environmental practices.",
    },
    caseStudy: "A startup under investor pressure to grow fast started aggressive marketing that annoyed existing customers with spam-like messaging. Short-term growth metrics improved (pleasing investors) but customer trust and retention dropped — showing how optimising for one stakeholder can hurt another.",
    founderQuestion: "If you had to rank customers, employees, and investors in order of priority during a crisis, what order would you choose, and why?",
    quiz: [
      { id: "d6q1", question: "Which of these is NOT typically considered a stakeholder?", options: ["Suppliers", "Competitors' customers who never interact with you", "Employees", "Government"], correctIndex: 1, explanation: "A stakeholder must have some interest in or influence on your specific business." },
      { id: "d6q2", question: "Why is stakeholder mapping useful before a major business decision?", options: ["It's legally required", "It reveals who benefits and who is hurt by the decision", "It guarantees profit", "It replaces financial analysis"], correctIndex: 1, explanation: "Mapping stakeholders helps anticipate consequences and manage trade-offs responsibly." },
      { id: "d6q3", question: "In the CEFISGPS mnemonic, what does the second 'S' stand for?", options: ["Sales", "Society", "Suppliers", "Strategy"], correctIndex: 1, explanation: "The two S's are Suppliers and Society." },
    ],
    takeaways: [
      "A stakeholder is anyone affected by or influencing the business.",
      "Key groups: customers, employees, founders, investors, suppliers, government, partners, society.",
      "Decisions often help one stakeholder while hurting another — map this before deciding.",
      "Ignoring a stakeholder group doesn't make them disappear; it just delays the consequence.",
    ],
    rememberThis: "Every business decision has ripple effects — map who gets the ripple before you make the splash.",
  },
  {
    id: "day-7", day: 7, phaseId: "business", slug: "business-thinking-day",
    title: "Business Thinking Day",
    objective: "Apply everything learned in Days 1-6 to a single realistic business scenario.",
    concept:
      "This is a review and application day. You'll take a simple business idea and systematically break it down using every lens learned so far: customer, problem, revenue, costs, business model, stakeholders, and profit. This kind of structured thinking is exactly what separates a founder from a daydreamer.",
    simpleExplanation: "Instead of learning something new, today you practice connecting Days 1-6 into one complete picture — the way a real founder would think through a new idea in 10 minutes flat.",
    analogy: "Think of this like a pilot's pre-flight checklist — before taking off with any idea, a founder runs through the same mental checklist every time.",
    businessExample: "Scenario: Imagine you start a ₹5,00,000 café. Customer = office workers nearby wanting quick, good coffee. Problem = limited good coffee options near their office. Solution = a fast, quality café. Revenue = coffee + snack sales. Business model = direct sales (pay per item). Stakeholders = customers, staff, landlord, suppliers (coffee beans), local government (licensing). Costs = rent, staff, raw materials, equipment. Profit = Revenue − Costs.",
    indiaExample: "Many Indian café chains (like Blue Tokai or Third Wave Coffee) started exactly this way — identifying office clusters with poor coffee options and building a focused, repeatable café format around that specific customer need.",
    startupExample: "This same checklist — customer, problem, solution, revenue, costs, model, stakeholders — is what investors expect a founder to answer clearly within the first 2 minutes of any pitch.",
    commonMistake: "Jumping straight to 'how do I build/open this' without first nailing down who the customer is and what problem they actually have. Solutions built before problems are understood usually fail.",
    exercise: {
      prompt: "Using the ₹5,00,000 café example, assume monthly revenue is ₹4,00,000 and monthly costs (rent + staff + materials) are ₹3,00,000. Calculate monthly profit and margin. Then list two stakeholders who are NOT customers or investors.",
      answer: "Profit = 4,00,000 − 3,00,000 = ₹1,00,000. Margin = (1,00,000 ÷ 4,00,000) × 100 = 25%. Other stakeholders: suppliers (coffee bean vendor) and local government (health/business licensing).",
    },
    caseStudy: "A founder opening a café skipped stakeholder analysis and signed a lease assuming low rent would mean high profit. She hadn't accounted for the local licensing authority's slow approval process, which delayed opening by 3 months and burned through her ₹5,00,000 budget before earning a single rupee — a reminder that stakeholders beyond customers and investors can make or break timing and cash flow.",
    founderQuestion: "Walk through your own café idea (or any ₹5,00,000 business idea) end-to-end: who is the customer, what's the problem, what's the model, who are all the stakeholders, and what's a realistic profit margin?",
    quiz: [
      { id: "d7q1", question: "What should a founder identify FIRST before building any solution?", options: ["The logo", "The customer and their problem", "The office location", "The investor pitch deck"], correctIndex: 1, explanation: "Solutions only make sense once the customer and problem are clearly understood." },
      { id: "d7q2", question: "In the café example, what is the business model?", options: ["Subscription", "Direct sales (pay per item)", "Advertising", "Licensing"], correctIndex: 1, explanation: "Customers pay directly for each coffee/snack purchased — a direct sales model." },
      { id: "d7q3", question: "Besides customers and investors, which stakeholder group affected the café's timeline in the case study?", options: ["Competitors", "Local government (licensing)", "Society", "Employees"], correctIndex: 1, explanation: "Licensing delays from local government authorities directly impacted the opening timeline and cash runway." },
    ],
    takeaways: [
      "Every business idea can be checked using the same framework: customer, problem, solution, revenue, costs, model, stakeholders, profit.",
      "Identify the customer and problem before designing the solution.",
      "Stakeholders beyond customers and investors (suppliers, government) often determine real-world timing and cost.",
      "Profit and margin calculations should be done early, even on rough estimates.",
    ],
    rememberThis: "Before building anything, run the full checklist: Who's the customer? What's their problem? How do I get paid? Who else is affected?",
  },
];
